# Copyright (c) 2016-2026, Université libre de Bruxelles and PyMEOS
# contributors. Licensed under the PostgreSQL License (see LICENSE).
#
# ============================================================================
#  GENERATED by tools/portable_aliases/generate.py -- DO NOT EDIT.
#  Regenerate:  python3 tools/portable_aliases/generate.py --headers <inc>
# ============================================================================
#
# The portable bare-name dialect (RFC #920; canonical contract:
# MobilityDB/MEOS-API meta/portable-aliases.json; native in MobilityDB via
# the 1303-alias PR #1075).  Every binding exposes the IDENTICAL bare names
# from that one mapping, type-agnostically across all six temporal type
# families (temporal, geo, cbuffer, npoint, pose, rgeo).
#
# Each bare name dispatches, by the runtime C type of its arguments, to the
# EXACT pymeos_cffi function the operator is backed by -- the same native
# call the type-qualified API uses.  Nothing is reimplemented: every bare
# name is identical to its operator by construction.
"""Portable bare-name dialect for PyMEOS (generated -- see module comment)."""
from __future__ import annotations

import datetime as _dt

# Resolved at call time so importing this module never requires the compiled
# binding to be present (e.g. docs / parity checks).
_cffi = None


def _pymeos_cffi():
    global _cffi
    if _cffi is None:
        import pymeos_cffi as _c

        _cffi = _c
    return _cffi


def _unwrap(a):
    return a._inner if hasattr(a, "_inner") else a


def _arg_token(a):
    """Runtime C base type of an argument, mirroring pymeos.factory's cdata
    field-sniffing (no ffi object needed) plus Python scalars."""
    if isinstance(a, bool):
        return "bool"
    if isinstance(a, int):
        return "int"
    if isinstance(a, float):
        return "float"
    if isinstance(a, str):
        return "text"
    if isinstance(a, _dt.datetime):
        return "timestamptz"
    if isinstance(a, _dt.date):
        return "date"
    if isinstance(a, _dt.timedelta):
        return "interval"
    o = _unwrap(a)
    for attr, tok in (
        ("temptype", "Temporal"),       # every temporal subtype (6 families)
        ("spansettype", "SpanSet"),
        ("spantype", "Span"),
        ("settype", "Set"),
    ):
        if hasattr(o, attr):
            return tok
    # Boxes / geo / spatial base types: distinguishing struct fields.
    for attr, tok in (
        ("srid", "STBox"),              # STBox carries an srid; TBox does not
        ("period", "TBox"),
        ("gflags", "GSERIALIZED"),
        ("rid", "Npoint"),
        ("radius", "Cbuffer"),
    ):
        if hasattr(o, attr):
            return tok
    return type(a).__name__


def _wrap(res):
    """Re-wrap MEOS-object results with the existing PyMEOS factories; pass
    scalars (bool/float/int/str) and None straight through."""
    if res is None or isinstance(res, (bool, int, float, str, bytes)):
        return res
    from .factory import _TemporalFactory, _CollectionFactory

    for fn in (_TemporalFactory.create_temporal,
               _CollectionFactory.create_collection):
        try:
            return fn(res)
        except Exception:
            pass
    return res


def _dispatch(name, table, args):
    key = tuple(_arg_token(a) for a in args)
    sym = table.get(key)
    if sym is None and len(key) == 2:           # symmetric fallback
        sym = table.get((key[1], key[0]))
    if sym is None:
        raise TypeError(
            f"{name}(): no portable overload for argument types {key}; "
            f"supported: {sorted(table)}"
        )
    fn = getattr(_pymeos_cffi(), sym)
    return _wrap(fn(*[_unwrap(a) for a in args]))

__all__ = ['above', 'adjacent', 'after', 'back', 'before', 'below', 'contained', 'contains', 'front', 'left', 'nearestApproachDistance', 'overabove', 'overafter', 'overback', 'overbefore', 'overbelow', 'overfront', 'overlaps', 'overleft', 'overright', 'right', 'same', 'tdistance', 'teq', 'tge', 'tgt', 'tle', 'tlt', 'tne']


_T_above = {('STBox', 'STBox'): 'above_stbox_stbox', ('STBox', 'Temporal'): 'above_stbox_tspatial', ('Temporal', 'STBox'): 'above_tspatial_stbox', ('Temporal', 'Temporal'): 'above_tspatial_tspatial'}


def above(*args):
    """Portable ``|>>`` (spaceY) -> pymeos_cffi backing call."""
    return _dispatch('above', _T_above, args)


_T_adjacent = {('Span', 'Temporal'): 'adjacent_tstzspan_temporal', ('Span', 'bigint'): 'adjacent_span_bigint', ('Span', 'date'): 'adjacent_span_date', ('Span', 'float'): 'adjacent_span_float', ('Span', 'int'): 'adjacent_span_int', ('Span', 'Span'): 'adjacent_span_span', ('Span', 'SpanSet'): 'adjacent_span_spanset', ('Span', 'timestamptz'): 'adjacent_span_timestamptz', ('Span', 'Datum'): 'adjacent_span_value', ('SpanSet', 'bigint'): 'adjacent_spanset_bigint', ('SpanSet', 'date'): 'adjacent_spanset_date', ('SpanSet', 'float'): 'adjacent_spanset_float', ('SpanSet', 'int'): 'adjacent_spanset_int', ('SpanSet', 'Span'): 'adjacent_spanset_span', ('SpanSet', 'SpanSet'): 'adjacent_spanset_spanset', ('SpanSet', 'timestamptz'): 'adjacent_spanset_timestamptz', ('SpanSet', 'Datum'): 'adjacent_spanset_value', ('STBox', 'STBox'): 'adjacent_stbox_stbox', ('STBox', 'Temporal'): 'adjacent_stbox_tspatial', ('TBox', 'TBox'): 'adjacent_tbox_tbox', ('TBox', 'Temporal'): 'adjacent_tbox_tnumber', ('Temporal', 'Temporal'): 'adjacent_tspatial_tspatial', ('Temporal', 'Span'): 'adjacent_tnumber_numspan', ('Temporal', 'TBox'): 'adjacent_tnumber_tbox', ('Temporal', 'STBox'): 'adjacent_tspatial_stbox', ('Datum', 'SpanSet'): 'adjacent_value_spanset'}


def adjacent(*args):
    """Portable ``-|-`` (topology) -> pymeos_cffi backing call."""
    return _dispatch('adjacent', _T_adjacent, args)


_T_after = {('date', 'Set'): 'after_date_set', ('date', 'Span'): 'after_date_span', ('date', 'SpanSet'): 'after_date_spanset', ('Set', 'date'): 'after_set_date', ('Set', 'timestamptz'): 'after_set_timestamptz', ('Span', 'date'): 'after_span_date', ('Span', 'timestamptz'): 'after_span_timestamptz', ('SpanSet', 'date'): 'after_spanset_date', ('SpanSet', 'timestamptz'): 'after_spanset_timestamptz', ('STBox', 'STBox'): 'after_stbox_stbox', ('STBox', 'Temporal'): 'after_stbox_tspatial', ('TBox', 'TBox'): 'after_tbox_tbox', ('TBox', 'Temporal'): 'after_tbox_tnumber', ('Temporal', 'Temporal'): 'after_tspatial_tspatial', ('Temporal', 'Span'): 'after_temporal_tstzspan', ('timestamptz', 'Set'): 'after_timestamptz_set', ('timestamptz', 'Span'): 'after_timestamptz_span', ('timestamptz', 'SpanSet'): 'after_timestamptz_spanset', ('Temporal', 'TBox'): 'after_tnumber_tbox', ('Temporal', 'STBox'): 'after_tspatial_stbox', ('Span', 'Temporal'): 'after_tstzspan_temporal'}


def after(*args):
    """Portable ``#>>`` (timePosition) -> pymeos_cffi backing call."""
    return _dispatch('after', _T_after, args)


_T_back = {('STBox', 'STBox'): 'back_stbox_stbox', ('STBox', 'Temporal'): 'back_stbox_tspatial', ('Temporal', 'STBox'): 'back_tspatial_stbox', ('Temporal', 'Temporal'): 'back_tspatial_tspatial'}


def back(*args):
    """Portable ``/>>`` (spaceZ) -> pymeos_cffi backing call."""
    return _dispatch('back', _T_back, args)


_T_before = {('date', 'Set'): 'before_date_set', ('date', 'Span'): 'before_date_span', ('date', 'SpanSet'): 'before_date_spanset', ('Set', 'date'): 'before_set_date', ('Set', 'timestamptz'): 'before_set_timestamptz', ('Span', 'date'): 'before_span_date', ('Span', 'timestamptz'): 'before_span_timestamptz', ('SpanSet', 'date'): 'before_spanset_date', ('SpanSet', 'timestamptz'): 'before_spanset_timestamptz', ('STBox', 'STBox'): 'before_stbox_stbox', ('STBox', 'Temporal'): 'before_stbox_tspatial', ('TBox', 'TBox'): 'before_tbox_tbox', ('TBox', 'Temporal'): 'before_tbox_tnumber', ('Temporal', 'Temporal'): 'before_tspatial_tspatial', ('Temporal', 'Span'): 'before_temporal_tstzspan', ('timestamptz', 'Set'): 'before_timestamptz_set', ('timestamptz', 'Span'): 'before_timestamptz_span', ('timestamptz', 'SpanSet'): 'before_timestamptz_spanset', ('Temporal', 'TBox'): 'before_tnumber_tbox', ('Temporal', 'STBox'): 'before_tspatial_stbox', ('Span', 'Temporal'): 'before_tstzspan_temporal'}


def before(*args):
    """Portable ``<<#`` (timePosition) -> pymeos_cffi backing call."""
    return _dispatch('before', _T_before, args)


_T_below = {('STBox', 'STBox'): 'below_stbox_stbox', ('STBox', 'Temporal'): 'below_stbox_tspatial', ('Temporal', 'STBox'): 'below_tspatial_stbox', ('Temporal', 'Temporal'): 'below_tspatial_tspatial'}


def below(*args):
    """Portable ``<<|`` (spaceY) -> pymeos_cffi backing call."""
    return _dispatch('below', _T_below, args)


_T_contained = {('bigint', 'Set'): 'contained_bigint_set', ('bigint', 'Span'): 'contained_bigint_span', ('bigint', 'SpanSet'): 'contained_bigint_spanset', ('Cbuffer', 'Set'): 'contained_cbuffer_set', ('date', 'Set'): 'contained_date_set', ('date', 'Span'): 'contained_date_span', ('date', 'SpanSet'): 'contained_date_spanset', ('float', 'Set'): 'contained_float_set', ('float', 'Span'): 'contained_float_span', ('float', 'SpanSet'): 'contained_float_spanset', ('GSERIALIZED', 'Set'): 'contained_geo_set', ('int', 'Set'): 'contained_int_set', ('int', 'Span'): 'contained_int_span', ('int', 'SpanSet'): 'contained_int_spanset', ('Jsonb', 'Set'): 'contained_jsonb_set', ('Npoint', 'Set'): 'contained_npoint_set', ('Span', 'Temporal'): 'contained_tstzspan_temporal', ('Pose', 'Set'): 'contained_pose_set', ('Set', 'Set'): 'contained_set_set', ('Span', 'Span'): 'contained_span_span', ('Span', 'SpanSet'): 'contained_span_spanset', ('SpanSet', 'Span'): 'contained_spanset_span', ('SpanSet', 'SpanSet'): 'contained_spanset_spanset', ('STBox', 'STBox'): 'contained_stbox_stbox', ('STBox', 'Temporal'): 'contained_stbox_tspatial', ('TBox', 'TBox'): 'contained_tbox_tbox', ('TBox', 'Temporal'): 'contained_tbox_tnumber', ('Temporal', 'Temporal'): 'contained_tspatial_tspatial', ('Temporal', 'Span'): 'contained_tnumber_numspan', ('text', 'Set'): 'contained_text_set', ('timestamptz', 'Set'): 'contained_timestamptz_set', ('timestamptz', 'Span'): 'contained_timestamptz_span', ('timestamptz', 'SpanSet'): 'contained_timestamptz_spanset', ('Temporal', 'TBox'): 'contained_tnumber_tbox', ('Temporal', 'STBox'): 'contained_tspatial_stbox', ('Datum', 'Set'): 'contained_value_set', ('Datum', 'Span'): 'contained_value_span', ('Datum', 'SpanSet'): 'contained_value_spanset'}


def contained(*args):
    """Portable ``<@`` (topology) -> pymeos_cffi backing call."""
    return _dispatch('contained', _T_contained, args)


_T_contains = {('Cbuffer', 'Cbuffer'): 'contains_cbuffer_cbuffer', ('Span', 'Temporal'): 'contains_tstzspan_temporal', ('Set', 'bigint'): 'contains_set_bigint', ('Set', 'Cbuffer'): 'contains_set_cbuffer', ('Set', 'date'): 'contains_set_date', ('Set', 'float'): 'contains_set_float', ('Set', 'GSERIALIZED'): 'contains_set_geo', ('Set', 'int'): 'contains_set_int', ('Set', 'Jsonb'): 'contains_set_jsonb', ('Set', 'Npoint'): 'contains_set_npoint', ('Set', 'Pose'): 'contains_set_pose', ('Set', 'Set'): 'contains_set_set', ('Set', 'text'): 'contains_set_text', ('Set', 'timestamptz'): 'contains_set_timestamptz', ('Set', 'Datum'): 'contains_set_value', ('Span', 'bigint'): 'contains_span_bigint', ('Span', 'date'): 'contains_span_date', ('Span', 'float'): 'contains_span_float', ('Span', 'int'): 'contains_span_int', ('Span', 'Span'): 'contains_span_span', ('Span', 'SpanSet'): 'contains_span_spanset', ('Span', 'timestamptz'): 'contains_span_timestamptz', ('Span', 'Datum'): 'contains_span_value', ('SpanSet', 'bigint'): 'contains_spanset_bigint', ('SpanSet', 'date'): 'contains_spanset_date', ('SpanSet', 'float'): 'contains_spanset_float', ('SpanSet', 'int'): 'contains_spanset_int', ('SpanSet', 'Span'): 'contains_spanset_span', ('SpanSet', 'SpanSet'): 'contains_spanset_spanset', ('SpanSet', 'timestamptz'): 'contains_spanset_timestamptz', ('SpanSet', 'Datum'): 'contains_spanset_value', ('STBox', 'STBox'): 'contains_stbox_stbox', ('STBox', 'Temporal'): 'contains_stbox_tspatial', ('TBox', 'TBox'): 'contains_tbox_tbox', ('TBox', 'Temporal'): 'contains_tbox_tnumber', ('Temporal', 'Temporal'): 'contains_tspatial_tspatial', ('Temporal', 'Span'): 'contains_tnumber_numspan', ('Temporal', 'Jsonb', 'bool'): 'contains_tjsonb_jsonb', ('Temporal', 'TBox'): 'contains_tnumber_tbox', ('Temporal', 'STBox'): 'contains_tspatial_stbox'}


def contains(*args):
    """Portable ``@>`` (topology) -> pymeos_cffi backing call."""
    return _dispatch('contains', _T_contains, args)


_T_front = {('STBox', 'STBox'): 'front_stbox_stbox', ('STBox', 'Temporal'): 'front_stbox_tspatial', ('Temporal', 'STBox'): 'front_tspatial_stbox', ('Temporal', 'Temporal'): 'front_tspatial_tspatial'}


def front(*args):
    """Portable ``<</`` (spaceZ) -> pymeos_cffi backing call."""
    return _dispatch('front', _T_front, args)


_T_left = {('bigint', 'Set'): 'left_bigint_set', ('bigint', 'Span'): 'left_bigint_span', ('bigint', 'SpanSet'): 'left_bigint_spanset', ('float', 'Set'): 'left_float_set', ('float', 'Span'): 'left_float_span', ('float', 'SpanSet'): 'left_float_spanset', ('int', 'Set'): 'left_int_set', ('int', 'Span'): 'left_int_span', ('int', 'SpanSet'): 'left_int_spanset', ('Span', 'Temporal'): 'left_numspan_tnumber', ('Set', 'bigint'): 'left_set_bigint', ('Set', 'float'): 'left_set_float', ('Set', 'int'): 'left_set_int', ('Set', 'Set'): 'left_set_set', ('Set', 'text'): 'left_set_text', ('Set', 'Datum'): 'left_set_value', ('Span', 'bigint'): 'left_span_bigint', ('Span', 'float'): 'left_span_float', ('Span', 'int'): 'left_span_int', ('Span', 'Span'): 'left_span_span', ('Span', 'SpanSet'): 'left_span_spanset', ('Span', 'Datum'): 'left_span_value', ('SpanSet', 'bigint'): 'left_spanset_bigint', ('SpanSet', 'float'): 'left_spanset_float', ('SpanSet', 'int'): 'left_spanset_int', ('SpanSet', 'Span'): 'left_spanset_span', ('SpanSet', 'SpanSet'): 'left_spanset_spanset', ('SpanSet', 'Datum'): 'left_spanset_value', ('STBox', 'STBox'): 'left_stbox_stbox', ('STBox', 'Temporal'): 'left_stbox_tspatial', ('TBox', 'TBox'): 'left_tbox_tbox', ('TBox', 'Temporal'): 'left_tbox_tnumber', ('text', 'Set'): 'left_text_set', ('Temporal', 'Span'): 'left_tnumber_numspan', ('Temporal', 'TBox'): 'left_tnumber_tbox', ('Temporal', 'Temporal'): 'left_tspatial_tspatial', ('Temporal', 'STBox'): 'left_tspatial_stbox', ('Datum', 'Set'): 'left_value_set', ('Datum', 'Span'): 'left_value_span', ('Datum', 'SpanSet'): 'left_value_spanset'}


def left(*args):
    """Portable ``<<`` (spaceX) -> pymeos_cffi backing call."""
    return _dispatch('left', _T_left, args)


_T_nearestApproachDistance = {('Cbuffer', 'STBox'): 'nad_cbuffer_stbox', ('STBox', 'GSERIALIZED'): 'nad_stbox_geo', ('STBox', 'STBox'): 'nad_stbox_stbox', ('STBox', 'Temporal'): 'nad_stbox_trgeo', ('TBox', 'TBox'): 'nad_tboxint_tboxint', ('Temporal', 'Cbuffer'): 'nad_tcbuffer_cbuffer', ('Temporal', 'GSERIALIZED'): 'nad_trgeo_geo', ('Temporal', 'STBox'): 'nad_trgeo_stbox', ('Temporal', 'Temporal'): 'nad_trgeo_trgeo', ('Temporal', 'float'): 'nad_tfloat_float', ('Temporal', 'TBox'): 'nad_tnumber_tbox', ('Temporal', 'int'): 'nad_tint_int', ('Temporal', 'Npoint'): 'nad_tnpoint_npoint', ('Temporal', 'Datum'): 'nad_tnumber_number', ('Temporal', 'Pose'): 'nad_tpose_pose'}


def nearestApproachDistance(*args):
    """Portable ``|=|`` (distance) -> pymeos_cffi backing call."""
    return _dispatch('nearestApproachDistance', _T_nearestApproachDistance, args)


_T_overabove = {('STBox', 'STBox'): 'overabove_stbox_stbox', ('STBox', 'Temporal'): 'overabove_stbox_tspatial', ('Temporal', 'STBox'): 'overabove_tspatial_stbox', ('Temporal', 'Temporal'): 'overabove_tspatial_tspatial'}


def overabove(*args):
    """Portable ``|&>`` (spaceY) -> pymeos_cffi backing call."""
    return _dispatch('overabove', _T_overabove, args)


_T_overafter = {('date', 'Set'): 'overafter_date_set', ('date', 'Span'): 'overafter_date_span', ('date', 'SpanSet'): 'overafter_date_spanset', ('Set', 'date'): 'overafter_set_date', ('Set', 'timestamptz'): 'overafter_set_timestamptz', ('Span', 'date'): 'overafter_span_date', ('Span', 'timestamptz'): 'overafter_span_timestamptz', ('SpanSet', 'date'): 'overafter_spanset_date', ('SpanSet', 'timestamptz'): 'overafter_spanset_timestamptz', ('STBox', 'STBox'): 'overafter_stbox_stbox', ('STBox', 'Temporal'): 'overafter_stbox_tspatial', ('TBox', 'TBox'): 'overafter_tbox_tbox', ('TBox', 'Temporal'): 'overafter_tbox_tnumber', ('Temporal', 'Temporal'): 'overafter_tspatial_tspatial', ('Temporal', 'Span'): 'overafter_temporal_tstzspan', ('timestamptz', 'Set'): 'overafter_timestamptz_set', ('timestamptz', 'Span'): 'overafter_timestamptz_span', ('timestamptz', 'SpanSet'): 'overafter_timestamptz_spanset', ('Temporal', 'TBox'): 'overafter_tnumber_tbox', ('Temporal', 'STBox'): 'overafter_tspatial_stbox', ('Span', 'Temporal'): 'overafter_tstzspan_temporal'}


def overafter(*args):
    """Portable ``#&>`` (timePosition) -> pymeos_cffi backing call."""
    return _dispatch('overafter', _T_overafter, args)


_T_overback = {('STBox', 'STBox'): 'overback_stbox_stbox', ('STBox', 'Temporal'): 'overback_stbox_tspatial', ('Temporal', 'STBox'): 'overback_tspatial_stbox', ('Temporal', 'Temporal'): 'overback_tspatial_tspatial'}


def overback(*args):
    """Portable ``/&>`` (spaceZ) -> pymeos_cffi backing call."""
    return _dispatch('overback', _T_overback, args)


_T_overbefore = {('date', 'Set'): 'overbefore_date_set', ('date', 'Span'): 'overbefore_date_span', ('date', 'SpanSet'): 'overbefore_date_spanset', ('Set', 'date'): 'overbefore_set_date', ('Set', 'timestamptz'): 'overbefore_set_timestamptz', ('Span', 'date'): 'overbefore_span_date', ('Span', 'timestamptz'): 'overbefore_span_timestamptz', ('SpanSet', 'date'): 'overbefore_spanset_date', ('SpanSet', 'timestamptz'): 'overbefore_spanset_timestamptz', ('STBox', 'STBox'): 'overbefore_stbox_stbox', ('STBox', 'Temporal'): 'overbefore_stbox_tspatial', ('TBox', 'TBox'): 'overbefore_tbox_tbox', ('TBox', 'Temporal'): 'overbefore_tbox_tnumber', ('Temporal', 'Temporal'): 'overbefore_tspatial_tspatial', ('Temporal', 'Span'): 'overbefore_temporal_tstzspan', ('timestamptz', 'Set'): 'overbefore_timestamptz_set', ('timestamptz', 'Span'): 'overbefore_timestamptz_span', ('timestamptz', 'SpanSet'): 'overbefore_timestamptz_spanset', ('Temporal', 'TBox'): 'overbefore_tnumber_tbox', ('Temporal', 'STBox'): 'overbefore_tspatial_stbox', ('Span', 'Temporal'): 'overbefore_tstzspan_temporal'}


def overbefore(*args):
    """Portable ``&<#`` (timePosition) -> pymeos_cffi backing call."""
    return _dispatch('overbefore', _T_overbefore, args)


_T_overbelow = {('STBox', 'STBox'): 'overbelow_stbox_stbox', ('STBox', 'Temporal'): 'overbelow_stbox_tspatial', ('Temporal', 'STBox'): 'overbelow_tspatial_stbox', ('Temporal', 'Temporal'): 'overbelow_tspatial_tspatial'}


def overbelow(*args):
    """Portable ``&<|`` (spaceY) -> pymeos_cffi backing call."""
    return _dispatch('overbelow', _T_overbelow, args)


_T_overfront = {('STBox', 'STBox'): 'overfront_stbox_stbox', ('STBox', 'Temporal'): 'overfront_stbox_tspatial', ('Temporal', 'STBox'): 'overfront_tspatial_stbox', ('Temporal', 'Temporal'): 'overfront_tspatial_tspatial'}


def overfront(*args):
    """Portable ``&</`` (spaceZ) -> pymeos_cffi backing call."""
    return _dispatch('overfront', _T_overfront, args)


_T_overlaps = {('Span', 'Temporal'): 'overlaps_tstzspan_temporal', ('Set', 'Set'): 'overlaps_set_set', ('Span', 'Span'): 'overlaps_span_span', ('Span', 'SpanSet'): 'overlaps_span_spanset', ('SpanSet', 'Span'): 'overlaps_spanset_span', ('SpanSet', 'SpanSet'): 'overlaps_spanset_spanset', ('STBox', 'STBox'): 'overlaps_stbox_stbox', ('STBox', 'Temporal'): 'overlaps_stbox_tspatial', ('TBox', 'TBox'): 'overlaps_tbox_tbox', ('TBox', 'Temporal'): 'overlaps_tbox_tnumber', ('Temporal', 'Temporal'): 'overlaps_tspatial_tspatial', ('Temporal', 'Span'): 'overlaps_tnumber_numspan', ('Temporal', 'TBox'): 'overlaps_tnumber_tbox', ('Temporal', 'STBox'): 'overlaps_tspatial_stbox'}


def overlaps(*args):
    """Portable ``&&`` (topology) -> pymeos_cffi backing call."""
    return _dispatch('overlaps', _T_overlaps, args)


_T_overleft = {('bigint', 'Set'): 'overleft_bigint_set', ('bigint', 'Span'): 'overleft_bigint_span', ('bigint', 'SpanSet'): 'overleft_bigint_spanset', ('float', 'Set'): 'overleft_float_set', ('float', 'Span'): 'overleft_float_span', ('float', 'SpanSet'): 'overleft_float_spanset', ('int', 'Set'): 'overleft_int_set', ('int', 'Span'): 'overleft_int_span', ('int', 'SpanSet'): 'overleft_int_spanset', ('Span', 'Temporal'): 'overleft_numspan_tnumber', ('Set', 'bigint'): 'overleft_set_bigint', ('Set', 'float'): 'overleft_set_float', ('Set', 'int'): 'overleft_set_int', ('Set', 'Set'): 'overleft_set_set', ('Set', 'text'): 'overleft_set_text', ('Set', 'Datum'): 'overleft_set_value', ('Span', 'bigint'): 'overleft_span_bigint', ('Span', 'float'): 'overleft_span_float', ('Span', 'int'): 'overleft_span_int', ('Span', 'Span'): 'overleft_span_span', ('Span', 'SpanSet'): 'overleft_span_spanset', ('Span', 'Datum'): 'overleft_span_value', ('SpanSet', 'bigint'): 'overleft_spanset_bigint', ('SpanSet', 'float'): 'overleft_spanset_float', ('SpanSet', 'int'): 'overleft_spanset_int', ('SpanSet', 'Span'): 'overleft_spanset_span', ('SpanSet', 'SpanSet'): 'overleft_spanset_spanset', ('SpanSet', 'Datum'): 'overleft_spanset_value', ('STBox', 'STBox'): 'overleft_stbox_stbox', ('STBox', 'Temporal'): 'overleft_stbox_tspatial', ('TBox', 'TBox'): 'overleft_tbox_tbox', ('TBox', 'Temporal'): 'overleft_tbox_tnumber', ('text', 'Set'): 'overleft_text_set', ('Temporal', 'Span'): 'overleft_tnumber_numspan', ('Temporal', 'TBox'): 'overleft_tnumber_tbox', ('Temporal', 'Temporal'): 'overleft_tspatial_tspatial', ('Temporal', 'STBox'): 'overleft_tspatial_stbox', ('Datum', 'Set'): 'overleft_value_set', ('Datum', 'Span'): 'overleft_value_span', ('Datum', 'SpanSet'): 'overleft_value_spanset'}


def overleft(*args):
    """Portable ``&<`` (spaceX) -> pymeos_cffi backing call."""
    return _dispatch('overleft', _T_overleft, args)


_T_overright = {('bigint', 'Set'): 'overright_bigint_set', ('bigint', 'Span'): 'overright_bigint_span', ('bigint', 'SpanSet'): 'overright_bigint_spanset', ('float', 'Set'): 'overright_float_set', ('float', 'Span'): 'overright_float_span', ('float', 'SpanSet'): 'overright_float_spanset', ('int', 'Set'): 'overright_int_set', ('int', 'Span'): 'overright_int_span', ('int', 'SpanSet'): 'overright_int_spanset', ('Span', 'Temporal'): 'overright_numspan_tnumber', ('Set', 'bigint'): 'overright_set_bigint', ('Set', 'float'): 'overright_set_float', ('Set', 'int'): 'overright_set_int', ('Set', 'Set'): 'overright_set_set', ('Set', 'text'): 'overright_set_text', ('Set', 'Datum'): 'overright_set_value', ('Span', 'bigint'): 'overright_span_bigint', ('Span', 'float'): 'overright_span_float', ('Span', 'int'): 'overright_span_int', ('Span', 'Span'): 'overright_span_span', ('Span', 'SpanSet'): 'overright_span_spanset', ('Span', 'Datum'): 'overright_span_value', ('SpanSet', 'bigint'): 'overright_spanset_bigint', ('SpanSet', 'float'): 'overright_spanset_float', ('SpanSet', 'int'): 'overright_spanset_int', ('SpanSet', 'Span'): 'overright_spanset_span', ('SpanSet', 'SpanSet'): 'overright_spanset_spanset', ('SpanSet', 'Datum'): 'overright_spanset_value', ('STBox', 'STBox'): 'overright_stbox_stbox', ('STBox', 'Temporal'): 'overright_stbox_tspatial', ('TBox', 'TBox'): 'overright_tbox_tbox', ('TBox', 'Temporal'): 'overright_tbox_tnumber', ('text', 'Set'): 'overright_text_set', ('Temporal', 'Span'): 'overright_tnumber_numspan', ('Temporal', 'TBox'): 'overright_tnumber_tbox', ('Temporal', 'Temporal'): 'overright_tspatial_tspatial', ('Temporal', 'STBox'): 'overright_tspatial_stbox', ('Datum', 'Set'): 'overright_value_set', ('Datum', 'Span'): 'overright_value_span', ('Datum', 'SpanSet'): 'overright_value_spanset'}


def overright(*args):
    """Portable ``&>`` (spaceX) -> pymeos_cffi backing call."""
    return _dispatch('overright', _T_overright, args)


_T_right = {('bigint', 'Set'): 'right_bigint_set', ('bigint', 'Span'): 'right_bigint_span', ('bigint', 'SpanSet'): 'right_bigint_spanset', ('float', 'Set'): 'right_float_set', ('float', 'Span'): 'right_float_span', ('float', 'SpanSet'): 'right_float_spanset', ('int', 'Set'): 'right_int_set', ('int', 'Span'): 'right_int_span', ('int', 'SpanSet'): 'right_int_spanset', ('Span', 'Temporal'): 'right_numspan_tnumber', ('Set', 'bigint'): 'right_set_bigint', ('Set', 'float'): 'right_set_float', ('Set', 'int'): 'right_set_int', ('Set', 'Set'): 'right_set_set', ('Set', 'text'): 'right_set_text', ('Set', 'Datum'): 'right_set_value', ('Span', 'bigint'): 'right_span_bigint', ('Span', 'float'): 'right_span_float', ('Span', 'int'): 'right_span_int', ('Span', 'Span'): 'right_span_span', ('Span', 'SpanSet'): 'right_span_spanset', ('Span', 'Datum'): 'right_span_value', ('SpanSet', 'bigint'): 'right_spanset_bigint', ('SpanSet', 'float'): 'right_spanset_float', ('SpanSet', 'int'): 'right_spanset_int', ('SpanSet', 'Span'): 'right_spanset_span', ('SpanSet', 'SpanSet'): 'right_spanset_spanset', ('SpanSet', 'Datum'): 'right_spanset_value', ('STBox', 'STBox'): 'right_stbox_stbox', ('STBox', 'Temporal'): 'right_stbox_tspatial', ('TBox', 'TBox'): 'right_tbox_tbox', ('TBox', 'Temporal'): 'right_tbox_tnumber', ('text', 'Set'): 'right_text_set', ('Temporal', 'Span'): 'right_tnumber_numspan', ('Temporal', 'TBox'): 'right_tnumber_tbox', ('Temporal', 'Temporal'): 'right_tspatial_tspatial', ('Temporal', 'STBox'): 'right_tspatial_stbox', ('Datum', 'Set'): 'right_value_set', ('Datum', 'Span'): 'right_value_span', ('Datum', 'SpanSet'): 'right_value_spanset'}


def right(*args):
    """Portable ``>>`` (spaceX) -> pymeos_cffi backing call."""
    return _dispatch('right', _T_right, args)


_T_same = {('Span', 'Temporal'): 'same_tstzspan_temporal', ('STBox', 'STBox'): 'same_stbox_stbox', ('STBox', 'Temporal'): 'same_stbox_tspatial', ('TBox', 'TBox'): 'same_tbox_tbox', ('TBox', 'Temporal'): 'same_tbox_tnumber', ('Temporal', 'Temporal'): 'same_tspatial_tspatial', ('Temporal', 'Span'): 'same_tnumber_numspan', ('Temporal', 'TBox'): 'same_tnumber_tbox', ('Temporal', 'STBox'): 'same_tspatial_stbox'}


def same(*args):
    """Portable ``~=`` (same) -> pymeos_cffi backing call."""
    return _dispatch('same', _T_same, args)


_T_tdistance = {('Temporal', 'Cbuffer'): 'tdistance_tcbuffer_cbuffer', ('Temporal', 'GSERIALIZED'): 'tdistance_trgeo_geo', ('Temporal', 'Temporal'): 'tdistance_trgeo_trgeo', ('Temporal', 'float'): 'tdistance_tfloat_float', ('Temporal', 'int'): 'tdistance_tint_int', ('Temporal', 'Npoint'): 'tdistance_tnpoint_npoint', ('Temporal', 'Datum'): 'tdistance_tnumber_number', ('Temporal', 'Pose'): 'tdistance_tpose_pose'}


def tdistance(*args):
    """Portable ``<->`` (distance) -> pymeos_cffi backing call."""
    return _dispatch('tdistance', _T_tdistance, args)


_T_teq = {('bool', 'Temporal'): 'teq_bool_tbool', ('Cbuffer', 'Temporal'): 'teq_cbuffer_tcbuffer', ('float', 'Temporal'): 'teq_float_tfloat', ('GSERIALIZED', 'Temporal'): 'teq_geo_trgeo', ('int', 'Temporal'): 'teq_int_tint', ('Jsonb', 'Temporal'): 'teq_jsonb_tjsonb', ('Pose', 'Temporal'): 'teq_pose_tpose', ('Temporal', 'bool'): 'teq_tbool_bool', ('Temporal', 'Cbuffer'): 'teq_tcbuffer_cbuffer', ('Temporal', 'Temporal'): 'teq_temporal_temporal', ('text', 'Temporal'): 'teq_text_ttext', ('Temporal', 'float'): 'teq_tfloat_float', ('Temporal', 'GSERIALIZED'): 'teq_trgeo_geo', ('Temporal', 'int'): 'teq_tint_int', ('Temporal', 'Jsonb'): 'teq_tjsonb_jsonb', ('Temporal', 'Npoint'): 'teq_tnpoint_npoint', ('Temporal', 'Pose'): 'teq_tpose_pose', ('Temporal', 'text'): 'teq_ttext_text'}


def teq(*args):
    """Portable ``#=`` (temporalComparison) -> pymeos_cffi backing call."""
    return _dispatch('teq', _T_teq, args)


_T_tge = {('float', 'Temporal'): 'tge_float_tfloat', ('int', 'Temporal'): 'tge_int_tint', ('Temporal', 'Temporal'): 'tge_temporal_temporal', ('text', 'Temporal'): 'tge_text_ttext', ('Temporal', 'float'): 'tge_tfloat_float', ('Temporal', 'int'): 'tge_tint_int', ('Temporal', 'text'): 'tge_ttext_text'}


def tge(*args):
    """Portable ``#>=`` (temporalComparison) -> pymeos_cffi backing call."""
    return _dispatch('tge', _T_tge, args)


_T_tgt = {('float', 'Temporal'): 'tgt_float_tfloat', ('int', 'Temporal'): 'tgt_int_tint', ('Temporal', 'Temporal'): 'tgt_temporal_temporal', ('text', 'Temporal'): 'tgt_text_ttext', ('Temporal', 'float'): 'tgt_tfloat_float', ('Temporal', 'int'): 'tgt_tint_int', ('Temporal', 'text'): 'tgt_ttext_text'}


def tgt(*args):
    """Portable ``#>`` (temporalComparison) -> pymeos_cffi backing call."""
    return _dispatch('tgt', _T_tgt, args)


_T_tle = {('float', 'Temporal'): 'tle_float_tfloat', ('int', 'Temporal'): 'tle_int_tint', ('Temporal', 'Temporal'): 'tle_temporal_temporal', ('text', 'Temporal'): 'tle_text_ttext', ('Temporal', 'float'): 'tle_tfloat_float', ('Temporal', 'int'): 'tle_tint_int', ('Temporal', 'text'): 'tle_ttext_text'}


def tle(*args):
    """Portable ``#<=`` (temporalComparison) -> pymeos_cffi backing call."""
    return _dispatch('tle', _T_tle, args)


_T_tlt = {('float', 'Temporal'): 'tlt_float_tfloat', ('int', 'Temporal'): 'tlt_int_tint', ('Temporal', 'Temporal'): 'tlt_temporal_temporal', ('text', 'Temporal'): 'tlt_text_ttext', ('Temporal', 'float'): 'tlt_tfloat_float', ('Temporal', 'int'): 'tlt_tint_int', ('Temporal', 'text'): 'tlt_ttext_text'}


def tlt(*args):
    """Portable ``#<`` (temporalComparison) -> pymeos_cffi backing call."""
    return _dispatch('tlt', _T_tlt, args)


_T_tne = {('bool', 'Temporal'): 'tne_bool_tbool', ('Cbuffer', 'Temporal'): 'tne_cbuffer_tcbuffer', ('float', 'Temporal'): 'tne_float_tfloat', ('GSERIALIZED', 'Temporal'): 'tne_geo_trgeo', ('int', 'Temporal'): 'tne_int_tint', ('Jsonb', 'Temporal'): 'tne_jsonb_tjsonb', ('Pose', 'Temporal'): 'tne_pose_tpose', ('Temporal', 'bool'): 'tne_tbool_bool', ('Temporal', 'Cbuffer'): 'tne_tcbuffer_cbuffer', ('Temporal', 'Temporal'): 'tne_temporal_temporal', ('text', 'Temporal'): 'tne_text_ttext', ('Temporal', 'float'): 'tne_tfloat_float', ('Temporal', 'GSERIALIZED'): 'tne_trgeo_geo', ('Temporal', 'int'): 'tne_tint_int', ('Temporal', 'Jsonb'): 'tne_tjsonb_jsonb', ('Temporal', 'Npoint'): 'tne_tnpoint_npoint', ('Temporal', 'Pose'): 'tne_tpose_pose', ('Temporal', 'text'): 'tne_ttext_text'}


def tne(*args):
    """Portable ``#<>`` (temporalComparison) -> pymeos_cffi backing call."""
    return _dispatch('tne', _T_tne, args)
