# Copyright (c) 2016-2026, Université libre de Bruxelles and PyMEOS
# contributors. Licensed under the PostgreSQL License (see LICENSE).
#
# ============================================================================
#  GENERATED by tools/oo_codegen/codegen.py -- DO NOT EDIT.  DRAFT ARTIFACT.
#  Regenerate:  python3 tools/oo_codegen/codegen.py
# ============================================================================
#
# This is a NON-DESTRUCTIVE preview of the regular "cbuffer" OO method
# families synthesised from the vendored meos-idl.json.  It is NOT imported
# by the pymeos package (the directory is underscore-prefixed); it exists so
# a reviewer can diff this uniform, deterministic surface against the hand-
# written pymeos/main/*.py before any staged migration.
#
# Every generated method DISPATCHES, by the C-name token of its argument, to
# the EXACT pymeos_cffi backing function the hand-written method uses -- the
# same native call, never reimplemented (aliases-reuse-backing): each method
# is identical to its hand-written counterpart by construction.
"""Preview of generated regular OO methods for the cbuffer family."""
from __future__ import annotations

# Resolved lazily so importing this Draft module never requires the compiled
# binding (parity checks / docs).
_cffi = None


def _c():
    global _cffi
    if _cffi is None:
        import pymeos_cffi as _m

        _cffi = _m
    return _cffi


def _unwrap(a):
    return a._inner if hasattr(a, "_inner") else a


def _wrap(_r):
    """Re-wrap a MEOS-object result with the existing PyMEOS factories;
    scalars and None pass straight through (mirrors PR #87's _wrap)."""
    if _r is None or isinstance(_r, (bool, int, float, str, bytes)):
        return _r
    from pymeos.factory import _TemporalFactory, _CollectionFactory

    for fn in (_TemporalFactory.create_temporal,
               _CollectionFactory.create_collection):
        try:
            return fn(_r)
        except Exception:
            pass
    return _r


class Temporal:  # noqa: D101  (diff-readability stand-in for the real base)
    @staticmethod
    def _factory(_r):
        return _wrap(_r)


class TCbufferMethods:
    """Generated regular methods for the cbuffer family (preview)."""

    # MEOS Functions: always_eq_cbuffer_tcbuffer, always_eq_tcbuffer_cbuffer, always_eq_tcbuffer_tcbuffer
    def always_equal(self, other):
        """Generated regular `always_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tcbuffer': 'always_eq_cbuffer_tcbuffer', 'cbuffer': 'always_eq_tcbuffer_cbuffer'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"always_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r > 0

    # MEOS Functions: aintersects_tcbuffer_cbuffer, aintersects_tcbuffer_geo, aintersects_tcbuffer_tcbuffer
    def always_intersects(self, other):
        """Generated regular `always_intersects` -> exact pymeos_cffi backing call."""
        _disp = {'geo': 'aintersects_tcbuffer_geo', 'cbuffer': 'aintersects_tcbuffer_cbuffer', 'tcbuffer': 'aintersects_tcbuffer_tcbuffer'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"always_intersects(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r == 1

    # MEOS Functions: always_ne_cbuffer_tcbuffer, always_ne_tcbuffer_cbuffer, always_ne_tcbuffer_tcbuffer
    def always_not_equal(self, other):
        """Generated regular `always_not_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tcbuffer': 'always_ne_cbuffer_tcbuffer', 'cbuffer': 'always_ne_tcbuffer_cbuffer'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"always_not_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r > 0

    # MEOS Functions: atouches_tcbuffer_cbuffer, atouches_tcbuffer_geo, atouches_tcbuffer_tcbuffer
    def always_touches(self, other):
        """Generated regular `always_touches` -> exact pymeos_cffi backing call."""
        _disp = {'geo': 'atouches_tcbuffer_geo', 'cbuffer': 'atouches_tcbuffer_cbuffer', 'tcbuffer': 'atouches_tcbuffer_tcbuffer'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"always_touches(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r == 1

    # MEOS Functions: tcbuffer_at_cbuffer, tcbuffer_at_geom, tcbuffer_at_stbox
    def at(self, other):
        """Generated regular `at` -> exact pymeos_cffi backing call."""
        _disp = {'cbuffer': 'tcbuffer_at_cbuffer', 'geom': 'tcbuffer_at_geom', 'stbox': 'tcbuffer_at_stbox'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"at(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: tcontains_cbuffer_tcbuffer, tcontains_geo_tcbuffer, tcontains_tcbuffer_cbuffer, tcontains_tcbuffer_geo, tcontains_tcbuffer_tcbuffer
    def contains(self, other):
        """Generated regular `contains` -> exact pymeos_cffi backing call."""
        _disp = {'tcbuffer': 'tcontains_cbuffer_tcbuffer', 'geo': 'tcontains_tcbuffer_geo', 'cbuffer': 'tcontains_tcbuffer_cbuffer'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"contains(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: tcovers_cbuffer_tcbuffer, tcovers_geo_tcbuffer, tcovers_tcbuffer_cbuffer, tcovers_tcbuffer_geo, tcovers_tcbuffer_tcbuffer
    def covers(self, other):
        """Generated regular `covers` -> exact pymeos_cffi backing call."""
        _disp = {'tcbuffer': 'tcovers_cbuffer_tcbuffer', 'geo': 'tcovers_tcbuffer_geo', 'cbuffer': 'tcovers_tcbuffer_cbuffer'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"covers(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: tdisjoint_cbuffer_tcbuffer, tdisjoint_geo_tcbuffer, tdisjoint_tcbuffer_cbuffer, tdisjoint_tcbuffer_geo, tdisjoint_tcbuffer_tcbuffer
    def disjoint(self, other):
        """Generated regular `disjoint` -> exact pymeos_cffi backing call."""
        _disp = {'tcbuffer': 'tdisjoint_cbuffer_tcbuffer', 'geo': 'tdisjoint_tcbuffer_geo', 'cbuffer': 'tdisjoint_tcbuffer_cbuffer'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"disjoint(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: tdistance_tcbuffer_cbuffer, tdistance_tcbuffer_geo, tdistance_tcbuffer_tcbuffer
    def distance(self, other):
        """Generated regular `distance` -> exact pymeos_cffi backing call."""
        _disp = {'cbuffer': 'tdistance_tcbuffer_cbuffer', 'geo': 'tdistance_tcbuffer_geo', 'tcbuffer': 'tdistance_tcbuffer_tcbuffer'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"distance(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: ever_eq_cbuffer_tcbuffer, ever_eq_tcbuffer_cbuffer, ever_eq_tcbuffer_tcbuffer
    def ever_equal(self, other):
        """Generated regular `ever_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tcbuffer': 'ever_eq_cbuffer_tcbuffer', 'cbuffer': 'ever_eq_tcbuffer_cbuffer'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"ever_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r > 0

    # MEOS Functions: eintersects_tcbuffer_cbuffer, eintersects_tcbuffer_geo, eintersects_tcbuffer_tcbuffer
    def ever_intersects(self, other):
        """Generated regular `ever_intersects` -> exact pymeos_cffi backing call."""
        _disp = {'geo': 'eintersects_tcbuffer_geo', 'cbuffer': 'eintersects_tcbuffer_cbuffer', 'tcbuffer': 'eintersects_tcbuffer_tcbuffer'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"ever_intersects(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r == 1

    # MEOS Functions: ever_ne_cbuffer_tcbuffer, ever_ne_tcbuffer_cbuffer, ever_ne_tcbuffer_tcbuffer
    def ever_not_equal(self, other):
        """Generated regular `ever_not_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tcbuffer': 'ever_ne_cbuffer_tcbuffer', 'cbuffer': 'ever_ne_tcbuffer_cbuffer'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"ever_not_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r > 0

    # MEOS Functions: etouches_tcbuffer_cbuffer, etouches_tcbuffer_geo, etouches_tcbuffer_tcbuffer
    def ever_touches(self, other):
        """Generated regular `ever_touches` -> exact pymeos_cffi backing call."""
        _disp = {'geo': 'etouches_tcbuffer_geo', 'cbuffer': 'etouches_tcbuffer_cbuffer', 'tcbuffer': 'etouches_tcbuffer_tcbuffer'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"ever_touches(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r == 1

    # MEOS Functions: tintersects_cbuffer_tcbuffer, tintersects_geo_tcbuffer, tintersects_tcbuffer_cbuffer, tintersects_tcbuffer_geo, tintersects_tcbuffer_tcbuffer
    def intersects(self, other):
        """Generated regular `intersects` -> exact pymeos_cffi backing call."""
        _disp = {'tcbuffer': 'tintersects_cbuffer_tcbuffer', 'geo': 'tintersects_tcbuffer_geo', 'cbuffer': 'tintersects_tcbuffer_cbuffer'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"intersects(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: acontains_cbuffer_tcbuffer, acontains_geo_tcbuffer, acontains_tcbuffer_cbuffer, acontains_tcbuffer_geo
    def is_always_contains(self, other):
        """Generated regular `is_always_contains` -> exact pymeos_cffi backing call."""
        _disp = {'tcbuffer': 'acontains_cbuffer_tcbuffer', 'cbuffer': 'acontains_tcbuffer_cbuffer', 'geo': 'acontains_tcbuffer_geo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"is_always_contains(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r == 1

    # MEOS Functions: acovers_cbuffer_tcbuffer, acovers_geo_tcbuffer, acovers_tcbuffer_cbuffer, acovers_tcbuffer_geo
    def is_always_covers(self, other):
        """Generated regular `is_always_covers` -> exact pymeos_cffi backing call."""
        _disp = {'tcbuffer': 'acovers_cbuffer_tcbuffer', 'cbuffer': 'acovers_tcbuffer_cbuffer', 'geo': 'acovers_tcbuffer_geo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"is_always_covers(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r == 1

    # MEOS Functions: adisjoint_tcbuffer_cbuffer, adisjoint_tcbuffer_geo, adisjoint_tcbuffer_tcbuffer
    def is_always_disjoint(self, other):
        """Generated regular `is_always_disjoint` -> exact pymeos_cffi backing call."""
        _disp = {'geo': 'adisjoint_tcbuffer_geo', 'cbuffer': 'adisjoint_tcbuffer_cbuffer', 'tcbuffer': 'adisjoint_tcbuffer_tcbuffer'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"is_always_disjoint(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r == 1

    # MEOS Functions: adwithin_tcbuffer_cbuffer, adwithin_tcbuffer_geo, adwithin_tcbuffer_tcbuffer
    def is_always_within_distance(self, other):
        """Generated regular `is_always_within_distance` -> exact pymeos_cffi backing call."""
        _disp = {'geo': 'adwithin_tcbuffer_geo', 'cbuffer': 'adwithin_tcbuffer_cbuffer', 'tcbuffer': 'adwithin_tcbuffer_tcbuffer'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"is_always_within_distance(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r == 1

    # MEOS Functions: econtains_cbuffer_tcbuffer, econtains_tcbuffer_cbuffer, econtains_tcbuffer_geo
    def is_ever_contains(self, other):
        """Generated regular `is_ever_contains` -> exact pymeos_cffi backing call."""
        _disp = {'tcbuffer': 'econtains_cbuffer_tcbuffer', 'cbuffer': 'econtains_tcbuffer_cbuffer', 'geo': 'econtains_tcbuffer_geo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"is_ever_contains(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r == 1

    # MEOS Functions: ecovers_cbuffer_tcbuffer, ecovers_tcbuffer_cbuffer, ecovers_tcbuffer_geo, ecovers_tcbuffer_tcbuffer
    def is_ever_covers(self, other):
        """Generated regular `is_ever_covers` -> exact pymeos_cffi backing call."""
        _disp = {'tcbuffer': 'ecovers_cbuffer_tcbuffer', 'cbuffer': 'ecovers_tcbuffer_cbuffer', 'geo': 'ecovers_tcbuffer_geo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"is_ever_covers(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r == 1

    # MEOS Functions: edisjoint_tcbuffer_cbuffer, edisjoint_tcbuffer_geo
    def is_ever_disjoint(self, other):
        """Generated regular `is_ever_disjoint` -> exact pymeos_cffi backing call."""
        _disp = {'geo': 'edisjoint_tcbuffer_geo', 'cbuffer': 'edisjoint_tcbuffer_cbuffer'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"is_ever_disjoint(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r == 1

    # MEOS Functions: edwithin_tcbuffer_cbuffer, edwithin_tcbuffer_geo, edwithin_tcbuffer_tcbuffer
    def is_ever_within_distance(self, other):
        """Generated regular `is_ever_within_distance` -> exact pymeos_cffi backing call."""
        _disp = {'geo': 'edwithin_tcbuffer_geo', 'cbuffer': 'edwithin_tcbuffer_cbuffer', 'tcbuffer': 'edwithin_tcbuffer_tcbuffer'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"is_ever_within_distance(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r == 1

    # MEOS Functions: tcbuffer_minus_cbuffer, tcbuffer_minus_geom, tcbuffer_minus_stbox
    def minus(self, other):
        """Generated regular `minus` -> exact pymeos_cffi backing call."""
        _disp = {'cbuffer': 'tcbuffer_minus_cbuffer', 'geom': 'tcbuffer_minus_geom', 'stbox': 'tcbuffer_minus_stbox'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"minus(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: nad_cbuffer_stbox, nad_tcbuffer_cbuffer, nad_tcbuffer_geo, nad_tcbuffer_stbox, nad_tcbuffer_tcbuffer
    def nearest_approach_distance(self, other):
        """Generated regular `nearest_approach_distance` -> exact pymeos_cffi backing call."""
        _disp = {'stbox': 'nad_cbuffer_stbox', 'cbuffer': 'nad_tcbuffer_cbuffer', 'geo': 'nad_tcbuffer_geo', 'tcbuffer': 'nad_tcbuffer_tcbuffer'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"nearest_approach_distance(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r

    # MEOS Functions: nai_tcbuffer_cbuffer, nai_tcbuffer_geo, nai_tcbuffer_tcbuffer
    def nearest_approach_instant(self, other):
        """Generated regular `nearest_approach_instant` -> exact pymeos_cffi backing call."""
        _disp = {'cbuffer': 'nai_tcbuffer_cbuffer', 'geo': 'nai_tcbuffer_geo', 'tcbuffer': 'nai_tcbuffer_tcbuffer'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"nearest_approach_instant(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _wrap(_r)

    # MEOS Functions: shortestline_tcbuffer_cbuffer, shortestline_tcbuffer_geo, shortestline_tcbuffer_tcbuffer
    def shortest_line(self, other):
        """Generated regular `shortest_line` -> exact pymeos_cffi backing call."""
        _disp = {'cbuffer': 'shortestline_tcbuffer_cbuffer', 'geo': 'shortestline_tcbuffer_geo', 'tcbuffer': 'shortestline_tcbuffer_tcbuffer'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"shortest_line(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _wrap(_r)

    # MEOS Functions: teq_cbuffer_tcbuffer, teq_tcbuffer_cbuffer
    def temporal_equal(self, other):
        """Generated regular `temporal_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tcbuffer': 'teq_cbuffer_tcbuffer', 'cbuffer': 'teq_tcbuffer_cbuffer'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"temporal_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: tne_cbuffer_tcbuffer, tne_tcbuffer_cbuffer
    def temporal_not_equal(self, other):
        """Generated regular `temporal_not_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tcbuffer': 'tne_cbuffer_tcbuffer', 'cbuffer': 'tne_tcbuffer_cbuffer'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"temporal_not_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: ttouches_cbuffer_tcbuffer, ttouches_geo_tcbuffer, ttouches_tcbuffer_cbuffer, ttouches_tcbuffer_geo, ttouches_tcbuffer_tcbuffer
    def touches(self, other):
        """Generated regular `touches` -> exact pymeos_cffi backing call."""
        _disp = {'tcbuffer': 'ttouches_geo_tcbuffer', 'geo': 'ttouches_tcbuffer_geo', 'cbuffer': 'ttouches_tcbuffer_cbuffer'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"touches(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: tdwithin_geo_tcbuffer, tdwithin_tcbuffer_cbuffer, tdwithin_tcbuffer_geo, tdwithin_tcbuffer_tcbuffer
    def within_distance(self, other):
        """Generated regular `within_distance` -> exact pymeos_cffi backing call."""
        _disp = {'tcbuffer': 'tdwithin_geo_tcbuffer', 'geo': 'tdwithin_tcbuffer_geo', 'cbuffer': 'tdwithin_tcbuffer_cbuffer'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"within_distance(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)
