# Copyright (c) 2016-2026, Université libre de Bruxelles and PyMEOS
# contributors. Licensed under the PostgreSQL License (see LICENSE).
#
# ============================================================================
#  GENERATED by tools/oo_codegen/codegen.py -- DO NOT EDIT.  DRAFT ARTIFACT.
#  Regenerate:  python3 tools/oo_codegen/codegen.py
# ============================================================================
#
# This is a NON-DESTRUCTIVE preview of the regular "geo" OO method
# families synthesised from the vendored meos-idl.json.  It is NOT imported
# by the pymeos package (the directory is underscore-prefixed); it exists so
# a reviewer can diff this uniform, deterministic surface against the hand-
# written pymeos/main/*.py before any staged migration.
#
# Every generated method DISPATCHES, by the C-name token of its argument, to
# the EXACT pymeos_cffi backing function the hand-written method uses -- the
# same native call, never reimplemented (aliases-reuse-backing): each method
# is identical to its hand-written counterpart by construction.
"""Preview of generated regular OO methods for the geo family."""
from __future__ import annotations

# Resolved lazily so importing this Draft module never requires the compiled
# binding (parity checks / docs).
_cffi = None


def _c():
    global _cffi
    if _cffi is None:
        import pymeos_cffi as _m

        _cffi = _m
    return _cffi


def _unwrap(a):
    return a._inner if hasattr(a, "_inner") else a


def _wrap(_r):
    """Re-wrap a MEOS-object result with the existing PyMEOS factories;
    scalars and None pass straight through (mirrors PR #87's _wrap)."""
    if _r is None or isinstance(_r, (bool, int, float, str, bytes)):
        return _r
    from pymeos.factory import _TemporalFactory, _CollectionFactory

    for fn in (_TemporalFactory.create_temporal,
               _CollectionFactory.create_collection):
        try:
            return fn(_r)
        except Exception:
            pass
    return _r


class Temporal:  # noqa: D101  (diff-readability stand-in for the real base)
    @staticmethod
    def _factory(_r):
        return _wrap(_r)


class TGeoMethods:
    """Generated regular methods for the geo family (preview)."""

    # MEOS Functions: always_eq_geo_tgeo, always_eq_tgeo_geo, always_eq_tgeo_tgeo
    def always_equal(self, other):
        """Generated regular `always_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tgeo': 'always_eq_geo_tgeo', 'geo': 'always_eq_tgeo_geo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"always_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r > 0

    # MEOS Functions: aintersects_tgeo_geo, aintersects_tgeo_tgeo
    def always_intersects(self, other):
        """Generated regular `always_intersects` -> exact pymeos_cffi backing call."""
        _disp = {'geo': 'aintersects_tgeo_geo', 'tgeo': 'aintersects_tgeo_tgeo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"always_intersects(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r == 1

    # MEOS Functions: always_ne_geo_tgeo, always_ne_tgeo_geo, always_ne_tgeo_tgeo
    def always_not_equal(self, other):
        """Generated regular `always_not_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tgeo': 'always_ne_geo_tgeo', 'geo': 'always_ne_tgeo_geo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"always_not_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r > 0

    # MEOS Functions: atouches_tgeo_geo, atouches_tgeo_tgeo, atouches_tpoint_geo
    def always_touches(self, other):
        """Generated regular `always_touches` -> exact pymeos_cffi backing call."""
        _disp = {'geo': 'atouches_tgeo_geo', 'tgeo': 'atouches_tgeo_tgeo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"always_touches(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r == 1

    # MEOS Functions: tgeo_at_geom, tgeo_at_stbox, tgeo_at_value, tpoint_at_elevation, tpoint_at_geom, tpoint_at_value
    def at(self, other):
        """Generated regular `at` -> exact pymeos_cffi backing call."""
        _disp = {'geom': 'tgeo_at_geom', 'stbox': 'tgeo_at_stbox', 'value': 'tgeo_at_value', 'elevation': 'tpoint_at_elevation'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"at(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: tcontains_geo_tgeo, tcontains_tgeo_geo, tcontains_tgeo_tgeo
    def contains(self, other):
        """Generated regular `contains` -> exact pymeos_cffi backing call."""
        _disp = {'tgeo': 'tcontains_geo_tgeo', 'geo': 'tcontains_tgeo_geo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"contains(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: tcovers_geo_tgeo, tcovers_tgeo_geo, tcovers_tgeo_tgeo
    def covers(self, other):
        """Generated regular `covers` -> exact pymeos_cffi backing call."""
        _disp = {'tgeo': 'tcovers_geo_tgeo', 'geo': 'tcovers_tgeo_geo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"covers(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: tdisjoint_geo_tgeo, tdisjoint_tgeo_geo, tdisjoint_tgeo_tgeo
    def disjoint(self, other):
        """Generated regular `disjoint` -> exact pymeos_cffi backing call."""
        _disp = {'tgeo': 'tdisjoint_geo_tgeo', 'geo': 'tdisjoint_tgeo_geo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"disjoint(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: tdistance_tgeo_geo, tdistance_tgeo_tgeo
    def distance(self, other):
        """Generated regular `distance` -> exact pymeos_cffi backing call."""
        _disp = {'geo': 'tdistance_tgeo_geo', 'tgeo': 'tdistance_tgeo_tgeo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"distance(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: ever_eq_geo_tgeo, ever_eq_tgeo_geo, ever_eq_tgeo_tgeo
    def ever_equal(self, other):
        """Generated regular `ever_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tgeo': 'ever_eq_geo_tgeo', 'geo': 'ever_eq_tgeo_geo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"ever_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r > 0

    # MEOS Functions: eintersects_tgeo_geo, eintersects_tgeo_tgeo
    def ever_intersects(self, other):
        """Generated regular `ever_intersects` -> exact pymeos_cffi backing call."""
        _disp = {'geo': 'eintersects_tgeo_geo', 'tgeo': 'eintersects_tgeo_tgeo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"ever_intersects(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r == 1

    # MEOS Functions: ever_ne_geo_tgeo, ever_ne_tgeo_geo, ever_ne_tgeo_tgeo
    def ever_not_equal(self, other):
        """Generated regular `ever_not_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tgeo': 'ever_ne_geo_tgeo', 'geo': 'ever_ne_tgeo_geo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"ever_not_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r > 0

    # MEOS Functions: etouches_tgeo_geo, etouches_tgeo_tgeo, etouches_tpoint_geo
    def ever_touches(self, other):
        """Generated regular `ever_touches` -> exact pymeos_cffi backing call."""
        _disp = {'geo': 'etouches_tgeo_geo', 'tgeo': 'etouches_tgeo_tgeo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"ever_touches(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r == 1

    # MEOS Functions: tintersects_geo_tgeo, tintersects_tgeo_geo, tintersects_tgeo_tgeo
    def intersects(self, other):
        """Generated regular `intersects` -> exact pymeos_cffi backing call."""
        _disp = {'tgeo': 'tintersects_geo_tgeo', 'geo': 'tintersects_tgeo_geo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"intersects(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: acontains_geo_tgeo, acontains_tgeo_geo, acontains_tgeo_tgeo
    def is_always_contains(self, other):
        """Generated regular `is_always_contains` -> exact pymeos_cffi backing call."""
        _disp = {'tgeo': 'acontains_geo_tgeo', 'geo': 'acontains_tgeo_geo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"is_always_contains(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r == 1

    # MEOS Functions: adisjoint_tgeo_geo, adisjoint_tgeo_tgeo
    def is_always_disjoint(self, other):
        """Generated regular `is_always_disjoint` -> exact pymeos_cffi backing call."""
        _disp = {'geo': 'adisjoint_tgeo_geo', 'tgeo': 'adisjoint_tgeo_tgeo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"is_always_disjoint(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r == 1

    # MEOS Functions: adwithin_tgeo_geo, adwithin_tgeo_tgeo
    def is_always_within_distance(self, other):
        """Generated regular `is_always_within_distance` -> exact pymeos_cffi backing call."""
        _disp = {'geo': 'adwithin_tgeo_geo', 'tgeo': 'adwithin_tgeo_tgeo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"is_always_within_distance(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r == 1

    # MEOS Functions: econtains_geo_tgeo, econtains_tgeo_geo, econtains_tgeo_tgeo
    def is_ever_contains(self, other):
        """Generated regular `is_ever_contains` -> exact pymeos_cffi backing call."""
        _disp = {'tgeo': 'econtains_geo_tgeo', 'geo': 'econtains_tgeo_geo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"is_ever_contains(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r == 1

    # MEOS Functions: ecovers_geo_tgeo, ecovers_tgeo_geo, ecovers_tgeo_tgeo
    def is_ever_covers(self, other):
        """Generated regular `is_ever_covers` -> exact pymeos_cffi backing call."""
        _disp = {'tgeo': 'ecovers_geo_tgeo', 'geo': 'ecovers_tgeo_geo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"is_ever_covers(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r == 1

    # MEOS Functions: edisjoint_tgeo_geo, edisjoint_tgeo_tgeo
    def is_ever_disjoint(self, other):
        """Generated regular `is_ever_disjoint` -> exact pymeos_cffi backing call."""
        _disp = {'geo': 'edisjoint_tgeo_geo', 'tgeo': 'edisjoint_tgeo_tgeo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"is_ever_disjoint(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r == 1

    # MEOS Functions: edwithin_tgeo_geo, edwithin_tgeo_tgeo
    def is_ever_within_distance(self, other):
        """Generated regular `is_ever_within_distance` -> exact pymeos_cffi backing call."""
        _disp = {'geo': 'edwithin_tgeo_geo', 'tgeo': 'edwithin_tgeo_tgeo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"is_ever_within_distance(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r == 1

    # MEOS Functions: tgeo_minus_geom, tgeo_minus_stbox, tgeo_minus_value, tpoint_minus_elevation, tpoint_minus_geom, tpoint_minus_value
    def minus(self, other):
        """Generated regular `minus` -> exact pymeos_cffi backing call."""
        _disp = {'geom': 'tgeo_minus_geom', 'stbox': 'tgeo_minus_stbox', 'value': 'tgeo_minus_value', 'elevation': 'tpoint_minus_elevation'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"minus(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: nad_stbox_geo, nad_tgeo_geo, nad_tgeo_stbox, nad_tgeo_tgeo
    def nearest_approach_distance(self, other):
        """Generated regular `nearest_approach_distance` -> exact pymeos_cffi backing call."""
        _disp = {'geo': 'nad_stbox_geo', 'stbox': 'nad_tgeo_stbox', 'tgeo': 'nad_tgeo_tgeo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"nearest_approach_distance(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r

    # MEOS Functions: nai_tgeo_geo, nai_tgeo_tgeo
    def nearest_approach_instant(self, other):
        """Generated regular `nearest_approach_instant` -> exact pymeos_cffi backing call."""
        _disp = {'geo': 'nai_tgeo_geo', 'tgeo': 'nai_tgeo_tgeo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"nearest_approach_instant(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _wrap(_r)

    # MEOS Functions: shortestline_tgeo_geo, shortestline_tgeo_tgeo
    def shortest_line(self, other):
        """Generated regular `shortest_line` -> exact pymeos_cffi backing call."""
        _disp = {'geo': 'shortestline_tgeo_geo', 'tgeo': 'shortestline_tgeo_tgeo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"shortest_line(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _wrap(_r)

    # MEOS Functions: teq_geo_tgeo, teq_tgeo_geo
    def temporal_equal(self, other):
        """Generated regular `temporal_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tgeo': 'teq_geo_tgeo', 'geo': 'teq_tgeo_geo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"temporal_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: tne_geo_tgeo, tne_tgeo_geo
    def temporal_not_equal(self, other):
        """Generated regular `temporal_not_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tgeo': 'tne_geo_tgeo', 'geo': 'tne_tgeo_geo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"temporal_not_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: ttouches_geo_tgeo, ttouches_tgeo_geo, ttouches_tgeo_tgeo
    def touches(self, other):
        """Generated regular `touches` -> exact pymeos_cffi backing call."""
        _disp = {'tgeo': 'ttouches_geo_tgeo', 'geo': 'ttouches_tgeo_geo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"touches(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: tdwithin_geo_tgeo, tdwithin_tgeo_geo, tdwithin_tgeo_tgeo
    def within_distance(self, other):
        """Generated regular `within_distance` -> exact pymeos_cffi backing call."""
        _disp = {'tgeo': 'tdwithin_geo_tgeo', 'geo': 'tdwithin_tgeo_geo'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"within_distance(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)
