# Copyright (c) 2016-2026, Université libre de Bruxelles and PyMEOS
# contributors. Licensed under the PostgreSQL License (see LICENSE).
#
# ============================================================================
#  GENERATED by tools/oo_codegen/codegen.py -- DO NOT EDIT.  DRAFT ARTIFACT.
#  Regenerate:  python3 tools/oo_codegen/codegen.py
# ============================================================================
#
# This is a NON-DESTRUCTIVE preview of the regular "npoint" OO method
# families synthesised from the vendored meos-idl.json.  It is NOT imported
# by the pymeos package (the directory is underscore-prefixed); it exists so
# a reviewer can diff this uniform, deterministic surface against the hand-
# written pymeos/main/*.py before any staged migration.
#
# Every generated method DISPATCHES, by the C-name token of its argument, to
# the EXACT pymeos_cffi backing function the hand-written method uses -- the
# same native call, never reimplemented (aliases-reuse-backing): each method
# is identical to its hand-written counterpart by construction.
"""Preview of generated regular OO methods for the npoint family."""
from __future__ import annotations

# Resolved lazily so importing this Draft module never requires the compiled
# binding (parity checks / docs).
_cffi = None


def _c():
    global _cffi
    if _cffi is None:
        import pymeos_cffi as _m

        _cffi = _m
    return _cffi


def _unwrap(a):
    return a._inner if hasattr(a, "_inner") else a


def _wrap(_r):
    """Re-wrap a MEOS-object result with the existing PyMEOS factories;
    scalars and None pass straight through (mirrors PR #87's _wrap)."""
    if _r is None or isinstance(_r, (bool, int, float, str, bytes)):
        return _r
    from pymeos.factory import _TemporalFactory, _CollectionFactory

    for fn in (_TemporalFactory.create_temporal,
               _CollectionFactory.create_collection):
        try:
            return fn(_r)
        except Exception:
            pass
    return _r


class Temporal:  # noqa: D101  (diff-readability stand-in for the real base)
    @staticmethod
    def _factory(_r):
        return _wrap(_r)


class TNpointMethods:
    """Generated regular methods for the npoint family (preview)."""

    # MEOS Functions: always_eq_npoint_tnpoint, always_eq_tnpoint_npoint, always_eq_tnpoint_tnpoint
    def always_equal(self, other):
        """Generated regular `always_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tnpoint': 'always_eq_npoint_tnpoint', 'npoint': 'always_eq_tnpoint_npoint'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"always_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r > 0

    # MEOS Functions: always_ne_npoint_tnpoint, always_ne_tnpoint_npoint, always_ne_tnpoint_tnpoint
    def always_not_equal(self, other):
        """Generated regular `always_not_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tnpoint': 'always_ne_npoint_tnpoint', 'npoint': 'always_ne_tnpoint_npoint'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"always_not_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r > 0

    # MEOS Functions: tnpoint_at_geom, tnpoint_at_npoint, tnpoint_at_npointset, tnpoint_at_stbox
    def at(self, other):
        """Generated regular `at` -> exact pymeos_cffi backing call."""
        _disp = {'geom': 'tnpoint_at_geom', 'npoint': 'tnpoint_at_npoint', 'npointset': 'tnpoint_at_npointset', 'stbox': 'tnpoint_at_stbox'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"at(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: tdistance_tnpoint_npoint, tdistance_tnpoint_point, tdistance_tnpoint_tnpoint
    def distance(self, other):
        """Generated regular `distance` -> exact pymeos_cffi backing call."""
        _disp = {'npoint': 'tdistance_tnpoint_npoint', 'point': 'tdistance_tnpoint_point', 'tnpoint': 'tdistance_tnpoint_tnpoint'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"distance(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: ever_eq_npoint_tnpoint, ever_eq_tnpoint_npoint, ever_eq_tnpoint_tnpoint
    def ever_equal(self, other):
        """Generated regular `ever_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tnpoint': 'ever_eq_npoint_tnpoint', 'npoint': 'ever_eq_tnpoint_npoint'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"ever_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r > 0

    # MEOS Functions: ever_ne_npoint_tnpoint, ever_ne_tnpoint_npoint, ever_ne_tnpoint_tnpoint
    def ever_not_equal(self, other):
        """Generated regular `ever_not_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tnpoint': 'ever_ne_npoint_tnpoint', 'npoint': 'ever_ne_tnpoint_npoint'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"ever_not_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r > 0

    # MEOS Functions: tnpoint_minus_geom, tnpoint_minus_npoint, tnpoint_minus_npointset, tnpoint_minus_stbox
    def minus(self, other):
        """Generated regular `minus` -> exact pymeos_cffi backing call."""
        _disp = {'geom': 'tnpoint_minus_geom', 'npoint': 'tnpoint_minus_npoint', 'npointset': 'tnpoint_minus_npointset', 'stbox': 'tnpoint_minus_stbox'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"minus(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: nad_tnpoint_geo, nad_tnpoint_npoint, nad_tnpoint_stbox, nad_tnpoint_tnpoint
    def nearest_approach_distance(self, other):
        """Generated regular `nearest_approach_distance` -> exact pymeos_cffi backing call."""
        _disp = {'geo': 'nad_tnpoint_geo', 'npoint': 'nad_tnpoint_npoint', 'stbox': 'nad_tnpoint_stbox', 'tnpoint': 'nad_tnpoint_tnpoint'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"nearest_approach_distance(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r

    # MEOS Functions: nai_tnpoint_geo, nai_tnpoint_npoint, nai_tnpoint_tnpoint
    def nearest_approach_instant(self, other):
        """Generated regular `nearest_approach_instant` -> exact pymeos_cffi backing call."""
        _disp = {'geo': 'nai_tnpoint_geo', 'npoint': 'nai_tnpoint_npoint', 'tnpoint': 'nai_tnpoint_tnpoint'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"nearest_approach_instant(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _wrap(_r)

    # MEOS Functions: shortestline_tnpoint_geo, shortestline_tnpoint_npoint, shortestline_tnpoint_tnpoint
    def shortest_line(self, other):
        """Generated regular `shortest_line` -> exact pymeos_cffi backing call."""
        _disp = {'geo': 'shortestline_tnpoint_geo', 'npoint': 'shortestline_tnpoint_npoint', 'tnpoint': 'shortestline_tnpoint_tnpoint'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"shortest_line(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _wrap(_r)

    # MEOS Functions: teq_tnpoint_npoint
    def temporal_equal(self, other):
        """Generated regular `temporal_equal` -> exact pymeos_cffi backing call."""
        _disp = {'npoint': 'teq_tnpoint_npoint'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"temporal_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: tne_tnpoint_npoint
    def temporal_not_equal(self, other):
        """Generated regular `temporal_not_equal` -> exact pymeos_cffi backing call."""
        _disp = {'npoint': 'tne_tnpoint_npoint'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"temporal_not_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)
