# Copyright (c) 2016-2026, Université libre de Bruxelles and PyMEOS
# contributors. Licensed under the PostgreSQL License (see LICENSE).
#
# ============================================================================
#  GENERATED by tools/oo_codegen/codegen.py -- DO NOT EDIT.  DRAFT ARTIFACT.
#  Regenerate:  python3 tools/oo_codegen/codegen.py
# ============================================================================
#
# This is a NON-DESTRUCTIVE preview of the regular "pose" OO method
# families synthesised from the vendored meos-idl.json.  It is NOT imported
# by the pymeos package (the directory is underscore-prefixed); it exists so
# a reviewer can diff this uniform, deterministic surface against the hand-
# written pymeos/main/*.py before any staged migration.
#
# Every generated method DISPATCHES, by the C-name token of its argument, to
# the EXACT pymeos_cffi backing function the hand-written method uses -- the
# same native call, never reimplemented (aliases-reuse-backing): each method
# is identical to its hand-written counterpart by construction.
"""Preview of generated regular OO methods for the pose family."""
from __future__ import annotations

# Resolved lazily so importing this Draft module never requires the compiled
# binding (parity checks / docs).
_cffi = None


def _c():
    global _cffi
    if _cffi is None:
        import pymeos_cffi as _m

        _cffi = _m
    return _cffi


def _unwrap(a):
    return a._inner if hasattr(a, "_inner") else a


def _wrap(_r):
    """Re-wrap a MEOS-object result with the existing PyMEOS factories;
    scalars and None pass straight through (mirrors PR #87's _wrap)."""
    if _r is None or isinstance(_r, (bool, int, float, str, bytes)):
        return _r
    from pymeos.factory import _TemporalFactory, _CollectionFactory

    for fn in (_TemporalFactory.create_temporal,
               _CollectionFactory.create_collection):
        try:
            return fn(_r)
        except Exception:
            pass
    return _r


class Temporal:  # noqa: D101  (diff-readability stand-in for the real base)
    @staticmethod
    def _factory(_r):
        return _wrap(_r)


class TPoseMethods:
    """Generated regular methods for the pose family (preview)."""

    # MEOS Functions: always_eq_pose_tpose, always_eq_tpose_pose, always_eq_tpose_tpose
    def always_equal(self, other):
        """Generated regular `always_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tpose': 'always_eq_pose_tpose', 'pose': 'always_eq_tpose_pose'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"always_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r > 0

    # MEOS Functions: always_ne_pose_tpose, always_ne_tpose_pose, always_ne_tpose_tpose
    def always_not_equal(self, other):
        """Generated regular `always_not_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tpose': 'always_ne_pose_tpose', 'pose': 'always_ne_tpose_pose'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"always_not_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r > 0

    # MEOS Functions: tpose_at_geom, tpose_at_pose, tpose_at_stbox
    def at(self, other):
        """Generated regular `at` -> exact pymeos_cffi backing call."""
        _disp = {'geom': 'tpose_at_geom', 'stbox': 'tpose_at_stbox', 'pose': 'tpose_at_pose'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"at(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: tdistance_tpose_point, tdistance_tpose_pose, tdistance_tpose_tpose
    def distance(self, other):
        """Generated regular `distance` -> exact pymeos_cffi backing call."""
        _disp = {'pose': 'tdistance_tpose_pose', 'point': 'tdistance_tpose_point', 'tpose': 'tdistance_tpose_tpose'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"distance(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: ever_eq_pose_tpose, ever_eq_tpose_pose, ever_eq_tpose_tpose
    def ever_equal(self, other):
        """Generated regular `ever_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tpose': 'ever_eq_pose_tpose', 'pose': 'ever_eq_tpose_pose'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"ever_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r > 0

    # MEOS Functions: ever_ne_pose_tpose, ever_ne_tpose_pose, ever_ne_tpose_tpose
    def ever_not_equal(self, other):
        """Generated regular `ever_not_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tpose': 'ever_ne_pose_tpose', 'pose': 'ever_ne_tpose_pose'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"ever_not_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r > 0

    # MEOS Functions: tpose_minus_geom, tpose_minus_pose, tpose_minus_stbox
    def minus(self, other):
        """Generated regular `minus` -> exact pymeos_cffi backing call."""
        _disp = {'geom': 'tpose_minus_geom', 'pose': 'tpose_minus_pose', 'stbox': 'tpose_minus_stbox'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"minus(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: nad_tpose_geo, nad_tpose_pose, nad_tpose_stbox, nad_tpose_tpose
    def nearest_approach_distance(self, other):
        """Generated regular `nearest_approach_distance` -> exact pymeos_cffi backing call."""
        _disp = {'geo': 'nad_tpose_geo', 'pose': 'nad_tpose_pose', 'stbox': 'nad_tpose_stbox', 'tpose': 'nad_tpose_tpose'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"nearest_approach_distance(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r

    # MEOS Functions: nai_tpose_geo, nai_tpose_pose, nai_tpose_tpose
    def nearest_approach_instant(self, other):
        """Generated regular `nearest_approach_instant` -> exact pymeos_cffi backing call."""
        _disp = {'geo': 'nai_tpose_geo', 'pose': 'nai_tpose_pose', 'tpose': 'nai_tpose_tpose'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"nearest_approach_instant(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _wrap(_r)

    # MEOS Functions: shortestline_tpose_geo, shortestline_tpose_pose, shortestline_tpose_tpose
    def shortest_line(self, other):
        """Generated regular `shortest_line` -> exact pymeos_cffi backing call."""
        _disp = {'geo': 'shortestline_tpose_geo', 'pose': 'shortestline_tpose_pose', 'tpose': 'shortestline_tpose_tpose'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"shortest_line(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _wrap(_r)

    # MEOS Functions: teq_pose_tpose, teq_tpose_pose
    def temporal_equal(self, other):
        """Generated regular `temporal_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tpose': 'teq_pose_tpose', 'pose': 'teq_tpose_pose'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"temporal_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: tne_pose_tpose, tne_tpose_pose
    def temporal_not_equal(self, other):
        """Generated regular `temporal_not_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tpose': 'tne_pose_tpose', 'pose': 'tne_tpose_pose'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"temporal_not_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)
