# Copyright (c) 2016-2026, Université libre de Bruxelles and PyMEOS
# contributors. Licensed under the PostgreSQL License (see LICENSE).
#
# ============================================================================
#  GENERATED by tools/oo_codegen/codegen.py -- DO NOT EDIT.  DRAFT ARTIFACT.
#  Regenerate:  python3 tools/oo_codegen/codegen.py
# ============================================================================
#
# This is a NON-DESTRUCTIVE preview of the regular "temporal" OO method
# families synthesised from the vendored meos-idl.json.  It is NOT imported
# by the pymeos package (the directory is underscore-prefixed); it exists so
# a reviewer can diff this uniform, deterministic surface against the hand-
# written pymeos/main/*.py before any staged migration.
#
# Every generated method DISPATCHES, by the C-name token of its argument, to
# the EXACT pymeos_cffi backing function the hand-written method uses -- the
# same native call, never reimplemented (aliases-reuse-backing): each method
# is identical to its hand-written counterpart by construction.
"""Preview of generated regular OO methods for the temporal family."""
from __future__ import annotations

# Resolved lazily so importing this Draft module never requires the compiled
# binding (parity checks / docs).
_cffi = None


def _c():
    global _cffi
    if _cffi is None:
        import pymeos_cffi as _m

        _cffi = _m
    return _cffi


def _unwrap(a):
    return a._inner if hasattr(a, "_inner") else a


def _wrap(_r):
    """Re-wrap a MEOS-object result with the existing PyMEOS factories;
    scalars and None pass straight through (mirrors PR #87's _wrap)."""
    if _r is None or isinstance(_r, (bool, int, float, str, bytes)):
        return _r
    from pymeos.factory import _TemporalFactory, _CollectionFactory

    for fn in (_TemporalFactory.create_temporal,
               _CollectionFactory.create_collection):
        try:
            return fn(_r)
        except Exception:
            pass
    return _r


class Temporal:  # noqa: D101  (diff-readability stand-in for the real base)
    @staticmethod
    def _factory(_r):
        return _wrap(_r)


class TTemporalMethods:
    """Generated regular methods for the temporal family (preview)."""

    # MEOS Functions: always_eq_bool_tbool, always_eq_float_tfloat, always_eq_int_tint, always_eq_tbool_bool, always_eq_temporal_temporal, always_eq_text_ttext, always_eq_tfloat_float, always_eq_tint_int, always_eq_ttext_text
    def always_equal(self, other):
        """Generated regular `always_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tbool': 'always_eq_bool_tbool', 'tfloat': 'always_eq_float_tfloat', 'tint': 'always_eq_int_tint', 'bool': 'always_eq_tbool_bool', 'temporal': 'always_eq_temporal_temporal', 'ttext': 'always_eq_text_ttext', 'float': 'always_eq_tfloat_float', 'int': 'always_eq_tint_int', 'text': 'always_eq_ttext_text'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"always_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r > 0

    # MEOS Functions: always_ne_bool_tbool, always_ne_float_tfloat, always_ne_int_tint, always_ne_tbool_bool, always_ne_temporal_temporal, always_ne_text_ttext, always_ne_tfloat_float, always_ne_tint_int, always_ne_ttext_text
    def always_not_equal(self, other):
        """Generated regular `always_not_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tbool': 'always_ne_bool_tbool', 'tfloat': 'always_ne_float_tfloat', 'tint': 'always_ne_int_tint', 'bool': 'always_ne_tbool_bool', 'temporal': 'always_ne_temporal_temporal', 'ttext': 'always_ne_text_ttext', 'float': 'always_ne_tfloat_float', 'int': 'always_ne_tint_int', 'text': 'always_ne_ttext_text'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"always_not_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r > 0

    # MEOS Functions: tbool_at_value, temporal_at_max, temporal_at_min, temporal_at_timestamptz, temporal_at_tstzset, temporal_at_tstzspan, temporal_at_tstzspanset, temporal_at_values, tfloat_at_value, tint_at_value, tnumber_at_span, tnumber_at_spanset, tnumber_at_tbox, ttext_at_value
    def at(self, other):
        """Generated regular `at` -> exact pymeos_cffi backing call."""
        _disp = {'value': 'tbool_at_value', 'max': 'temporal_at_max', 'min': 'temporal_at_min', 'timestamptz': 'temporal_at_timestamptz', 'tstzset': 'temporal_at_tstzset', 'tstzspan': 'temporal_at_tstzspan', 'tstzspanset': 'temporal_at_tstzspanset', 'values': 'temporal_at_values', 'span': 'tnumber_at_span', 'spanset': 'tnumber_at_spanset', 'tbox': 'tnumber_at_tbox'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"at(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: tdistance_tfloat_float, tdistance_tint_int, tdistance_tnumber_tnumber
    def distance(self, other):
        """Generated regular `distance` -> exact pymeos_cffi backing call."""
        _disp = {'float': 'tdistance_tfloat_float', 'int': 'tdistance_tint_int', 'tnumber': 'tdistance_tnumber_tnumber'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"distance(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: ever_eq_bool_tbool, ever_eq_float_tfloat, ever_eq_int_tint, ever_eq_tbool_bool, ever_eq_temporal_temporal, ever_eq_text_ttext, ever_eq_tfloat_float, ever_eq_tint_int, ever_eq_ttext_text
    def ever_equal(self, other):
        """Generated regular `ever_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tbool': 'ever_eq_bool_tbool', 'tfloat': 'ever_eq_float_tfloat', 'tint': 'ever_eq_int_tint', 'bool': 'ever_eq_tbool_bool', 'temporal': 'ever_eq_temporal_temporal', 'ttext': 'ever_eq_text_ttext', 'float': 'ever_eq_tfloat_float', 'int': 'ever_eq_tint_int', 'text': 'ever_eq_ttext_text'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"ever_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r > 0

    # MEOS Functions: ever_ne_bool_tbool, ever_ne_float_tfloat, ever_ne_int_tint, ever_ne_tbool_bool, ever_ne_temporal_temporal, ever_ne_text_ttext, ever_ne_tfloat_float, ever_ne_tint_int, ever_ne_ttext_text
    def ever_not_equal(self, other):
        """Generated regular `ever_not_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tbool': 'ever_ne_bool_tbool', 'tfloat': 'ever_ne_float_tfloat', 'tint': 'ever_ne_int_tint', 'bool': 'ever_ne_tbool_bool', 'temporal': 'ever_ne_temporal_temporal', 'ttext': 'ever_ne_text_ttext', 'float': 'ever_ne_tfloat_float', 'int': 'ever_ne_tint_int', 'text': 'ever_ne_ttext_text'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"ever_not_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r > 0

    # MEOS Functions: tbool_minus_value, temporal_minus_max, temporal_minus_min, temporal_minus_timestamptz, temporal_minus_tstzset, temporal_minus_tstzspan, temporal_minus_tstzspanset, temporal_minus_values, tfloat_minus_value, tint_minus_value, tnumber_minus_span, tnumber_minus_spanset, tnumber_minus_tbox, ttext_minus_value
    def minus(self, other):
        """Generated regular `minus` -> exact pymeos_cffi backing call."""
        _disp = {'value': 'tbool_minus_value', 'max': 'temporal_minus_max', 'min': 'temporal_minus_min', 'timestamptz': 'temporal_minus_timestamptz', 'tstzset': 'temporal_minus_tstzset', 'tstzspan': 'temporal_minus_tstzspan', 'tstzspanset': 'temporal_minus_tstzspanset', 'values': 'temporal_minus_values', 'span': 'tnumber_minus_span', 'spanset': 'tnumber_minus_spanset', 'tbox': 'tnumber_minus_tbox'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"minus(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: nad_tfloat_float, nad_tfloat_tbox, nad_tfloat_tfloat, nad_tint_int, nad_tint_tbox, nad_tint_tint, nad_tnumber_tbox, nad_tnumber_tnumber
    def nearest_approach_distance(self, other):
        """Generated regular `nearest_approach_distance` -> exact pymeos_cffi backing call."""
        _disp = {'float': 'nad_tfloat_float', 'tfloat': 'nad_tfloat_tfloat', 'tbox': 'nad_tfloat_tbox', 'int': 'nad_tint_int', 'tint': 'nad_tint_tint', 'tnumber': 'nad_tnumber_tnumber'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"nearest_approach_distance(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return _r

    # MEOS Functions: teq_bool_tbool, teq_float_tfloat, teq_int_tint, teq_tbool_bool, teq_temporal_temporal, teq_text_ttext, teq_tfloat_float, teq_tint_int, teq_ttext_text
    def temporal_equal(self, other):
        """Generated regular `temporal_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tbool': 'teq_bool_tbool', 'tfloat': 'teq_float_tfloat', 'tint': 'teq_int_tint', 'bool': 'teq_tbool_bool', 'temporal': 'teq_temporal_temporal', 'ttext': 'teq_text_ttext', 'float': 'teq_tfloat_float', 'int': 'teq_tint_int', 'text': 'teq_ttext_text'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"temporal_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: tgt_float_tfloat, tgt_int_tint, tgt_temporal_temporal, tgt_text_ttext, tgt_tfloat_float, tgt_tint_int, tgt_ttext_text
    def temporal_greater(self, other):
        """Generated regular `temporal_greater` -> exact pymeos_cffi backing call."""
        _disp = {'tfloat': 'tgt_float_tfloat', 'tint': 'tgt_int_tint', 'temporal': 'tgt_temporal_temporal', 'ttext': 'tgt_text_ttext', 'float': 'tgt_tfloat_float', 'int': 'tgt_tint_int', 'text': 'tgt_ttext_text'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"temporal_greater(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: tge_float_tfloat, tge_int_tint, tge_temporal_temporal, tge_text_ttext, tge_tfloat_float, tge_tint_int, tge_ttext_text
    def temporal_greater_or_equal(self, other):
        """Generated regular `temporal_greater_or_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tfloat': 'tge_float_tfloat', 'tint': 'tge_int_tint', 'temporal': 'tge_temporal_temporal', 'ttext': 'tge_text_ttext', 'float': 'tge_tfloat_float', 'int': 'tge_tint_int', 'text': 'tge_ttext_text'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"temporal_greater_or_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: tlt_float_tfloat, tlt_int_tint, tlt_temporal_temporal, tlt_text_ttext, tlt_tfloat_float, tlt_tint_int, tlt_ttext_text
    def temporal_less(self, other):
        """Generated regular `temporal_less` -> exact pymeos_cffi backing call."""
        _disp = {'tfloat': 'tlt_float_tfloat', 'tint': 'tlt_int_tint', 'temporal': 'tlt_temporal_temporal', 'ttext': 'tlt_text_ttext', 'float': 'tlt_tfloat_float', 'int': 'tlt_tint_int', 'text': 'tlt_ttext_text'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"temporal_less(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: tle_float_tfloat, tle_int_tint, tle_temporal_temporal, tle_text_ttext, tle_tfloat_float, tle_tint_int, tle_ttext_text
    def temporal_less_or_equal(self, other):
        """Generated regular `temporal_less_or_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tfloat': 'tle_float_tfloat', 'tint': 'tle_int_tint', 'temporal': 'tle_temporal_temporal', 'ttext': 'tle_text_ttext', 'float': 'tle_tfloat_float', 'int': 'tle_tint_int', 'text': 'tle_ttext_text'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"temporal_less_or_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)

    # MEOS Functions: tne_bool_tbool, tne_float_tfloat, tne_int_tint, tne_tbool_bool, tne_temporal_temporal, tne_text_ttext, tne_tfloat_float, tne_tint_int, tne_ttext_text
    def temporal_not_equal(self, other):
        """Generated regular `temporal_not_equal` -> exact pymeos_cffi backing call."""
        _disp = {'tbool': 'tne_bool_tbool', 'tfloat': 'tne_float_tfloat', 'tint': 'tne_int_tint', 'bool': 'tne_tbool_bool', 'temporal': 'tne_temporal_temporal', 'ttext': 'tne_text_ttext', 'float': 'tne_tfloat_float', 'int': 'tne_tint_int', 'text': 'tne_ttext_text'}
        _key = getattr(other, "__meos_token__", type(other).__name__.lower())
        _sym = _disp.get(_key) or (next(iter(_disp.values()))
                                   if len(_disp) == 1 else None)
        if _sym is None:
            raise TypeError(
                f"temporal_not_equal(): no overload for {type(other).__name__}; "
                f"argument kinds: {sorted(_disp)}")
        _r = getattr(_c(), _sym)(self._inner, _unwrap(other))
        return Temporal._factory(_r)
