# Copyright (c) 2016-2026, Université libre de Bruxelles and PyMEOS
# contributors. Licensed under the PostgreSQL License (see LICENSE).
#
# ============================================================================
#  GENERATED by tools/oo_codegen/codegen.py -- DO NOT EDIT.
#  Regenerate:
#    python3 tools/oo_codegen/codegen.py --mixin geo \
#        --mixin-out pymeos/main/_generated/geo_methods.py
# ============================================================================
#
# Wired into pymeos.main.TPoint via TPointDispatchMixin.  Every method
# dispatches by argument type to the EXACT pymeos_cffi backing the
# hand-written method used -- same native call, same transforms, same
# result, never reimplemented: identical by construction.
"""Generated regular OO methods for the TPoint family."""
from __future__ import annotations

from typing import TYPE_CHECKING

import shapely.geometry.base as shpb
from pymeos_cffi import *

from ...temporal import Temporal
import shapely.geometry as shp
import shapely.geometry.base as shpb
from ...collections import GeoSet

if TYPE_CHECKING:
    from ..tpoint import TPoint, TGeogPoint


class TPointDispatchMixin:
    """Generated regular families (comparison, spatial relationship,
    distance, restriction) for :class:`TPoint`."""

    def at(self, other):
        """Generated regular ``at``.

        MEOS Functions:
            temporal_at_values, tgeo_at_stbox, tpoint_at_geom, tpoint_at_value
        """
        from ..tpoint import TPoint, TGeogPoint
        from ...boxes import STBox

        if isinstance(other, shp.Point):
            result = tpoint_at_value(
                self._inner, geo_to_gserialized(other, isinstance(self, TGeogPoint))
            )
        elif isinstance(other, shpb.BaseGeometry):
            result = tpoint_at_geom(
                self._inner, geo_to_gserialized(other, isinstance(self, TGeogPoint))
            )
        elif isinstance(other, GeoSet):
            result = temporal_at_values(self._inner, other._inner)
        elif isinstance(other, STBox):
            result = tgeo_at_stbox(self._inner, other._inner, True)
        else:
            return super().at(other)
        return Temporal._factory(result)

    def distance(self, other):
        """Generated regular ``distance``.

        MEOS Functions:
            tdistance_tgeo_geo, tdistance_tgeo_tgeo
        """
        from ..tpoint import TPoint, TGeogPoint
        from ...boxes import STBox

        if isinstance(other, shpb.BaseGeometry):
            result = tdistance_tgeo_geo(
                self._inner, geo_to_gserialized(other, isinstance(self, TGeogPoint))
            )
        elif isinstance(other, STBox):
            result = tdistance_tgeo_geo(self._inner, stbox_to_geo(other._inner))
        elif isinstance(other, TPoint):
            result = tdistance_tgeo_tgeo(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return Temporal._factory(result)

    def minus(self, other):
        """Generated regular ``minus``.

        MEOS Functions:
            temporal_minus_values, tgeo_minus_stbox, tpoint_minus_geom, tpoint_minus_value
        """
        from ..tpoint import TPoint, TGeogPoint
        from ...boxes import STBox

        if isinstance(other, shp.Point):
            result = tpoint_minus_value(
                self._inner, geo_to_gserialized(other, isinstance(self, TGeogPoint))
            )
        elif isinstance(other, shpb.BaseGeometry):
            result = tpoint_minus_geom(
                self._inner, geo_to_gserialized(other, isinstance(self, TGeogPoint))
            )
        elif isinstance(other, GeoSet):
            result = temporal_minus_values(self._inner, other._inner)
        elif isinstance(other, STBox):
            result = tgeo_minus_stbox(self._inner, other._inner, True)
        else:
            return super().minus(other)
        return Temporal._factory(result)

    def nearest_approach_distance(self, other):
        """Generated regular ``nearest_approach_distance``.

        MEOS Functions:
            nad_tgeo_geo, nad_tgeo_stbox, nad_tgeo_tgeo
        """
        from ..tpoint import TPoint, TGeogPoint
        from ...boxes import STBox

        if isinstance(other, shpb.BaseGeometry):
            result = nad_tgeo_geo(
                self._inner, geo_to_gserialized(other, isinstance(self, TGeogPoint))
            )
        elif isinstance(other, STBox):
            result = nad_tgeo_stbox(self._inner, other._inner)
        elif isinstance(other, TPoint):
            result = nad_tgeo_tgeo(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return result
