# Copyright (c) 2016-2026, Université libre de Bruxelles and PyMEOS
# contributors. Licensed under the PostgreSQL License (see LICENSE).
#
# ============================================================================
#  GENERATED by tools/oo_codegen/codegen.py -- DO NOT EDIT.
#  Regenerate:
#    python3 tools/oo_codegen/codegen.py --mixin cbuffer \
#        --mixin-out pymeos/main/_generated/cbuffer_methods.py
# ============================================================================
#
# Wired into pymeos.main.TCbuffer via TCbufferRegularMixin.  Every method
# dispatches by argument type to the EXACT pymeos_cffi backing the
# hand-written method used -- same native call, same transforms, same
# result, never reimplemented: identical by construction.
"""Generated regular OO methods for the TCbuffer family."""
from __future__ import annotations

from typing import TYPE_CHECKING

import shapely.geometry.base as shpb
from pymeos_cffi import *

from ...temporal import Temporal
from ...collections.cbuffer import Cbuffer

if TYPE_CHECKING:
    from ..tcbuffer import TCbuffer


class TCbufferRegularMixin:
    """Generated regular families (comparison, spatial relationship,
    distance, restriction) for :class:`TCbuffer`."""

    def always_equal(self, other):
        """Generated regular ``always_equal``.

        MEOS Functions:
            always_eq_cbuffer_tcbuffer, always_eq_tcbuffer_cbuffer, always_eq_tcbuffer_tcbuffer
        """
        from ..tcbuffer import TCbuffer

        if isinstance(other, Cbuffer):
            result = always_eq_tcbuffer_cbuffer(self._inner, other._inner)
        elif isinstance(other, TCbuffer):
            result = always_eq_tcbuffer_tcbuffer(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return result > 0

    def always_intersects(self, other):
        """Generated regular ``always_intersects``.

        MEOS Functions:
            aintersects_tcbuffer_cbuffer, aintersects_tcbuffer_geo, aintersects_tcbuffer_tcbuffer
        """
        from ..tcbuffer import TCbuffer

        if isinstance(other, shpb.BaseGeometry):
            result = aintersects_tcbuffer_geo(
                self._inner, geo_to_gserialized(other, False)
            )
        elif isinstance(other, Cbuffer):
            result = aintersects_tcbuffer_cbuffer(self._inner, other._inner)
        elif isinstance(other, TCbuffer):
            result = aintersects_tcbuffer_tcbuffer(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return result == 1

    def always_not_equal(self, other):
        """Generated regular ``always_not_equal``.

        MEOS Functions:
            always_ne_cbuffer_tcbuffer, always_ne_tcbuffer_cbuffer, always_ne_tcbuffer_tcbuffer
        """
        from ..tcbuffer import TCbuffer

        if isinstance(other, Cbuffer):
            result = always_ne_tcbuffer_cbuffer(self._inner, other._inner)
        elif isinstance(other, TCbuffer):
            result = always_ne_tcbuffer_tcbuffer(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return result > 0

    def always_touches(self, other):
        """Generated regular ``always_touches``.

        MEOS Functions:
            atouches_tcbuffer_cbuffer, atouches_tcbuffer_geo, atouches_tcbuffer_tcbuffer
        """
        from ..tcbuffer import TCbuffer

        if isinstance(other, shpb.BaseGeometry):
            result = atouches_tcbuffer_geo(
                self._inner, geo_to_gserialized(other, False)
            )
        elif isinstance(other, Cbuffer):
            result = atouches_tcbuffer_cbuffer(self._inner, other._inner)
        elif isinstance(other, TCbuffer):
            result = atouches_tcbuffer_tcbuffer(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return result == 1

    def at(self, other):
        """Generated regular ``at``.

        MEOS Functions:
            tcbuffer_at_cbuffer, tcbuffer_at_geom, tcbuffer_at_stbox
        """
        from ...boxes import STBox

        if isinstance(other, shpb.BaseGeometry):
            result = tcbuffer_at_geom(self._inner, geo_to_gserialized(other, False))
        elif isinstance(other, Cbuffer):
            result = tcbuffer_at_cbuffer(self._inner, other._inner)
        elif isinstance(other, STBox):
            result = tcbuffer_at_stbox(self._inner, other._inner, True)
        else:
            return super().at(other)
        return Temporal._factory(result)

    def contains(self, other):
        """Generated regular ``contains``.

        MEOS Functions:
            tcontains_cbuffer_tcbuffer, tcontains_geo_tcbuffer, tcontains_tcbuffer_cbuffer, tcontains_tcbuffer_geo, tcontains_tcbuffer_tcbuffer
        """
        from ..tcbuffer import TCbuffer

        if isinstance(other, shpb.BaseGeometry):
            result = tcontains_tcbuffer_geo(
                self._inner, geo_to_gserialized(other, False)
            )
        elif isinstance(other, Cbuffer):
            result = tcontains_tcbuffer_cbuffer(self._inner, other._inner)
        elif isinstance(other, TCbuffer):
            result = tcontains_tcbuffer_tcbuffer(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return Temporal._factory(result)

    def covers(self, other):
        """Generated regular ``covers``.

        MEOS Functions:
            tcovers_cbuffer_tcbuffer, tcovers_geo_tcbuffer, tcovers_tcbuffer_cbuffer, tcovers_tcbuffer_geo, tcovers_tcbuffer_tcbuffer
        """
        from ..tcbuffer import TCbuffer

        if isinstance(other, shpb.BaseGeometry):
            result = tcovers_tcbuffer_geo(self._inner, geo_to_gserialized(other, False))
        elif isinstance(other, Cbuffer):
            result = tcovers_tcbuffer_cbuffer(self._inner, other._inner)
        elif isinstance(other, TCbuffer):
            result = tcovers_tcbuffer_tcbuffer(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return Temporal._factory(result)

    def disjoint(self, other):
        """Generated regular ``disjoint``.

        MEOS Functions:
            tdisjoint_cbuffer_tcbuffer, tdisjoint_geo_tcbuffer, tdisjoint_tcbuffer_cbuffer, tdisjoint_tcbuffer_geo, tdisjoint_tcbuffer_tcbuffer
        """
        from ..tcbuffer import TCbuffer

        if isinstance(other, shpb.BaseGeometry):
            result = tdisjoint_tcbuffer_geo(
                self._inner, geo_to_gserialized(other, False)
            )
        elif isinstance(other, Cbuffer):
            result = tdisjoint_tcbuffer_cbuffer(self._inner, other._inner)
        elif isinstance(other, TCbuffer):
            result = tdisjoint_tcbuffer_tcbuffer(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return Temporal._factory(result)

    def distance(self, other):
        """Generated regular ``distance``.

        MEOS Functions:
            tdistance_tcbuffer_cbuffer, tdistance_tcbuffer_geo, tdistance_tcbuffer_tcbuffer
        """
        from ..tcbuffer import TCbuffer

        if isinstance(other, shpb.BaseGeometry):
            result = tdistance_tcbuffer_geo(
                self._inner, geo_to_gserialized(other, False)
            )
        elif isinstance(other, Cbuffer):
            result = tdistance_tcbuffer_cbuffer(self._inner, other._inner)
        elif isinstance(other, TCbuffer):
            result = tdistance_tcbuffer_tcbuffer(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return Temporal._factory(result)

    def ever_equal(self, other):
        """Generated regular ``ever_equal``.

        MEOS Functions:
            ever_eq_cbuffer_tcbuffer, ever_eq_tcbuffer_cbuffer, ever_eq_tcbuffer_tcbuffer
        """
        from ..tcbuffer import TCbuffer

        if isinstance(other, Cbuffer):
            result = ever_eq_tcbuffer_cbuffer(self._inner, other._inner)
        elif isinstance(other, TCbuffer):
            result = ever_eq_tcbuffer_tcbuffer(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return result > 0

    def ever_intersects(self, other):
        """Generated regular ``ever_intersects``.

        MEOS Functions:
            eintersects_tcbuffer_cbuffer, eintersects_tcbuffer_geo, eintersects_tcbuffer_tcbuffer
        """
        from ..tcbuffer import TCbuffer

        if isinstance(other, shpb.BaseGeometry):
            result = eintersects_tcbuffer_geo(
                self._inner, geo_to_gserialized(other, False)
            )
        elif isinstance(other, Cbuffer):
            result = eintersects_tcbuffer_cbuffer(self._inner, other._inner)
        elif isinstance(other, TCbuffer):
            result = eintersects_tcbuffer_tcbuffer(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return result == 1

    def ever_not_equal(self, other):
        """Generated regular ``ever_not_equal``.

        MEOS Functions:
            ever_ne_cbuffer_tcbuffer, ever_ne_tcbuffer_cbuffer, ever_ne_tcbuffer_tcbuffer
        """
        from ..tcbuffer import TCbuffer

        if isinstance(other, Cbuffer):
            result = ever_ne_tcbuffer_cbuffer(self._inner, other._inner)
        elif isinstance(other, TCbuffer):
            result = ever_ne_tcbuffer_tcbuffer(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return result > 0

    def ever_touches(self, other):
        """Generated regular ``ever_touches``.

        MEOS Functions:
            etouches_tcbuffer_cbuffer, etouches_tcbuffer_geo, etouches_tcbuffer_tcbuffer
        """
        from ..tcbuffer import TCbuffer

        if isinstance(other, shpb.BaseGeometry):
            result = etouches_tcbuffer_geo(
                self._inner, geo_to_gserialized(other, False)
            )
        elif isinstance(other, Cbuffer):
            result = etouches_tcbuffer_cbuffer(self._inner, other._inner)
        elif isinstance(other, TCbuffer):
            result = etouches_tcbuffer_tcbuffer(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return result == 1

    def intersects(self, other):
        """Generated regular ``intersects``.

        MEOS Functions:
            tintersects_cbuffer_tcbuffer, tintersects_geo_tcbuffer, tintersects_tcbuffer_cbuffer, tintersects_tcbuffer_geo, tintersects_tcbuffer_tcbuffer
        """
        from ..tcbuffer import TCbuffer

        if isinstance(other, shpb.BaseGeometry):
            result = tintersects_tcbuffer_geo(
                self._inner, geo_to_gserialized(other, False)
            )
        elif isinstance(other, Cbuffer):
            result = tintersects_tcbuffer_cbuffer(self._inner, other._inner)
        elif isinstance(other, TCbuffer):
            result = tintersects_tcbuffer_tcbuffer(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return Temporal._factory(result)

    def is_always_contains(self, other):
        """Generated regular ``is_always_contains``.

        MEOS Functions:
            acontains_cbuffer_tcbuffer, acontains_geo_tcbuffer, acontains_tcbuffer_cbuffer, acontains_tcbuffer_geo
        """
        if isinstance(other, shpb.BaseGeometry):
            result = acontains_tcbuffer_geo(
                self._inner, geo_to_gserialized(other, False)
            )
        elif isinstance(other, Cbuffer):
            result = acontains_tcbuffer_cbuffer(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return result == 1

    def is_always_covers(self, other):
        """Generated regular ``is_always_covers``.

        MEOS Functions:
            acovers_cbuffer_tcbuffer, acovers_geo_tcbuffer, acovers_tcbuffer_cbuffer, acovers_tcbuffer_geo
        """
        if isinstance(other, shpb.BaseGeometry):
            result = acovers_tcbuffer_geo(self._inner, geo_to_gserialized(other, False))
        elif isinstance(other, Cbuffer):
            result = acovers_tcbuffer_cbuffer(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return result == 1

    def is_always_disjoint(self, other):
        """Generated regular ``is_always_disjoint``.

        MEOS Functions:
            adisjoint_tcbuffer_cbuffer, adisjoint_tcbuffer_geo, adisjoint_tcbuffer_tcbuffer
        """
        from ..tcbuffer import TCbuffer

        if isinstance(other, shpb.BaseGeometry):
            result = adisjoint_tcbuffer_geo(
                self._inner, geo_to_gserialized(other, False)
            )
        elif isinstance(other, Cbuffer):
            result = adisjoint_tcbuffer_cbuffer(self._inner, other._inner)
        elif isinstance(other, TCbuffer):
            result = adisjoint_tcbuffer_tcbuffer(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return result == 1

    def is_always_within_distance(self, other, distance):
        """Generated regular ``is_always_within_distance``.

        MEOS Functions:
            adwithin_tcbuffer_cbuffer, adwithin_tcbuffer_geo, adwithin_tcbuffer_tcbuffer
        """
        from ..tcbuffer import TCbuffer

        if isinstance(other, shpb.BaseGeometry):
            result = adwithin_tcbuffer_geo(
                self._inner, geo_to_gserialized(other, False), distance
            )
        elif isinstance(other, Cbuffer):
            result = adwithin_tcbuffer_cbuffer(self._inner, other._inner, distance)
        elif isinstance(other, TCbuffer):
            result = adwithin_tcbuffer_tcbuffer(self._inner, other._inner, distance)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return result == 1

    def is_ever_contains(self, other):
        """Generated regular ``is_ever_contains``.

        MEOS Functions:
            econtains_cbuffer_tcbuffer, econtains_tcbuffer_cbuffer, econtains_tcbuffer_geo
        """
        if isinstance(other, shpb.BaseGeometry):
            result = econtains_tcbuffer_geo(
                self._inner, geo_to_gserialized(other, False)
            )
        elif isinstance(other, Cbuffer):
            result = econtains_tcbuffer_cbuffer(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return result == 1

    def is_ever_covers(self, other):
        """Generated regular ``is_ever_covers``.

        MEOS Functions:
            ecovers_cbuffer_tcbuffer, ecovers_tcbuffer_cbuffer, ecovers_tcbuffer_geo, ecovers_tcbuffer_tcbuffer
        """
        from ..tcbuffer import TCbuffer

        if isinstance(other, shpb.BaseGeometry):
            result = ecovers_tcbuffer_geo(self._inner, geo_to_gserialized(other, False))
        elif isinstance(other, Cbuffer):
            result = ecovers_tcbuffer_cbuffer(self._inner, other._inner)
        elif isinstance(other, TCbuffer):
            result = ecovers_tcbuffer_tcbuffer(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return result == 1

    def is_ever_disjoint(self, other):
        """Generated regular ``is_ever_disjoint``.

        MEOS Functions:
            edisjoint_tcbuffer_cbuffer, edisjoint_tcbuffer_geo
        """
        if isinstance(other, shpb.BaseGeometry):
            result = edisjoint_tcbuffer_geo(
                self._inner, geo_to_gserialized(other, False)
            )
        elif isinstance(other, Cbuffer):
            result = edisjoint_tcbuffer_cbuffer(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return result == 1

    def is_ever_within_distance(self, other, distance):
        """Generated regular ``is_ever_within_distance``.

        MEOS Functions:
            edwithin_tcbuffer_cbuffer, edwithin_tcbuffer_geo, edwithin_tcbuffer_tcbuffer
        """
        from ..tcbuffer import TCbuffer

        if isinstance(other, shpb.BaseGeometry):
            result = edwithin_tcbuffer_geo(
                self._inner, geo_to_gserialized(other, False), distance
            )
        elif isinstance(other, Cbuffer):
            result = edwithin_tcbuffer_cbuffer(self._inner, other._inner, distance)
        elif isinstance(other, TCbuffer):
            result = edwithin_tcbuffer_tcbuffer(self._inner, other._inner, distance)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return result == 1

    def minus(self, other):
        """Generated regular ``minus``.

        MEOS Functions:
            tcbuffer_minus_cbuffer, tcbuffer_minus_geom, tcbuffer_minus_stbox
        """
        from ...boxes import STBox

        if isinstance(other, shpb.BaseGeometry):
            result = tcbuffer_minus_geom(self._inner, geo_to_gserialized(other, False))
        elif isinstance(other, Cbuffer):
            result = tcbuffer_minus_cbuffer(self._inner, other._inner)
        elif isinstance(other, STBox):
            result = tcbuffer_minus_stbox(self._inner, other._inner, True)
        else:
            return super().minus(other)
        return Temporal._factory(result)

    def nearest_approach_distance(self, other):
        """Generated regular ``nearest_approach_distance``.

        MEOS Functions:
            nad_cbuffer_stbox, nad_tcbuffer_cbuffer, nad_tcbuffer_geo, nad_tcbuffer_stbox, nad_tcbuffer_tcbuffer
        """
        from ..tcbuffer import TCbuffer
        from ...boxes import STBox

        if isinstance(other, shpb.BaseGeometry):
            result = nad_tcbuffer_geo(self._inner, geo_to_gserialized(other, False))
        elif isinstance(other, Cbuffer):
            result = nad_tcbuffer_cbuffer(self._inner, other._inner)
        elif isinstance(other, TCbuffer):
            result = nad_tcbuffer_tcbuffer(self._inner, other._inner)
        elif isinstance(other, STBox):
            result = nad_tcbuffer_stbox(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return result

    def nearest_approach_instant(self, other):
        """Generated regular ``nearest_approach_instant``.

        MEOS Functions:
            nai_tcbuffer_cbuffer, nai_tcbuffer_geo, nai_tcbuffer_tcbuffer
        """
        from ..tcbuffer import TCbuffer

        if isinstance(other, shpb.BaseGeometry):
            result = nai_tcbuffer_geo(self._inner, geo_to_gserialized(other, False))
        elif isinstance(other, Cbuffer):
            result = nai_tcbuffer_cbuffer(self._inner, other._inner)
        elif isinstance(other, TCbuffer):
            result = nai_tcbuffer_tcbuffer(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return Temporal._factory(result)

    def shortest_line(self, other):
        """Generated regular ``shortest_line``.

        MEOS Functions:
            shortestline_tcbuffer_cbuffer, shortestline_tcbuffer_geo, shortestline_tcbuffer_tcbuffer
        """
        from ..tcbuffer import TCbuffer

        if isinstance(other, shpb.BaseGeometry):
            result = shortestline_tcbuffer_geo(
                self._inner, geo_to_gserialized(other, False)
            )
        elif isinstance(other, Cbuffer):
            result = shortestline_tcbuffer_cbuffer(self._inner, other._inner)
        elif isinstance(other, TCbuffer):
            result = shortestline_tcbuffer_tcbuffer(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return gserialized_to_shapely_geometry(result, 10)

    def temporal_equal(self, other):
        """Generated regular ``temporal_equal``.

        MEOS Functions:
            teq_cbuffer_tcbuffer, teq_tcbuffer_cbuffer
        """
        if isinstance(other, Cbuffer):
            result = teq_tcbuffer_cbuffer(self._inner, other._inner)
        else:
            return super().temporal_equal(other)
        return Temporal._factory(result)

    def temporal_not_equal(self, other):
        """Generated regular ``temporal_not_equal``.

        MEOS Functions:
            tne_cbuffer_tcbuffer, tne_tcbuffer_cbuffer
        """
        if isinstance(other, Cbuffer):
            result = tne_tcbuffer_cbuffer(self._inner, other._inner)
        else:
            return super().temporal_not_equal(other)
        return Temporal._factory(result)

    def touches(self, other):
        """Generated regular ``touches``.

        MEOS Functions:
            ttouches_cbuffer_tcbuffer, ttouches_geo_tcbuffer, ttouches_tcbuffer_cbuffer, ttouches_tcbuffer_geo, ttouches_tcbuffer_tcbuffer
        """
        from ..tcbuffer import TCbuffer

        if isinstance(other, shpb.BaseGeometry):
            result = ttouches_tcbuffer_geo(
                self._inner, geo_to_gserialized(other, False)
            )
        elif isinstance(other, Cbuffer):
            result = ttouches_tcbuffer_cbuffer(self._inner, other._inner)
        elif isinstance(other, TCbuffer):
            result = ttouches_tcbuffer_tcbuffer(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return Temporal._factory(result)

    def within_distance(self, other, distance):
        """Generated regular ``within_distance``.

        MEOS Functions:
            tdwithin_geo_tcbuffer, tdwithin_tcbuffer_cbuffer, tdwithin_tcbuffer_geo, tdwithin_tcbuffer_tcbuffer
        """
        from ..tcbuffer import TCbuffer

        if isinstance(other, shpb.BaseGeometry):
            result = tdwithin_tcbuffer_geo(
                self._inner, geo_to_gserialized(other, False), distance
            )
        elif isinstance(other, Cbuffer):
            result = tdwithin_tcbuffer_cbuffer(self._inner, other._inner, distance)
        elif isinstance(other, TCbuffer):
            result = tdwithin_tcbuffer_tcbuffer(self._inner, other._inner, distance)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return Temporal._factory(result)
