# Copyright (c) 2016-2026, Université libre de Bruxelles and PyMEOS
# contributors. Licensed under the PostgreSQL License (see LICENSE).
#
# ============================================================================
#  GENERATED by tools/oo_codegen/codegen.py -- DO NOT EDIT.
#  Regenerate:
#    python3 tools/oo_codegen/codegen.py --mixin tfloat \
#        --mixin-out pymeos/main/_generated/tfloat_methods.py
# ============================================================================
#
# Wired into pymeos.main.TFloat via TFloatDispatchMixin.  Every method
# dispatches by argument type to the EXACT pymeos_cffi backing the
# hand-written method used -- same native call, same transforms, same
# result, never reimplemented: identical by construction.
"""Generated regular OO methods for the TFloat family."""
from __future__ import annotations

from typing import TYPE_CHECKING

import shapely.geometry.base as shpb
from pymeos_cffi import *

from ...temporal import Temporal
from ...collections import IntSet, IntSpan, IntSpanSet

if TYPE_CHECKING:
    from ..tfloat import TFloat


class TFloatDispatchMixin:
    """Generated regular families (comparison, spatial relationship,
    distance, restriction) for :class:`TFloat`."""

    def always_equal(self, other):
        """Generated regular ``always_equal``.

        MEOS Functions:
            always_eq_temporal_temporal, always_eq_tfloat_float
        """
        from ..tfloat import TFloat

        if isinstance(other, float):
            result = always_eq_tfloat_float(self._inner, other)
        elif isinstance(other, TFloat):
            result = always_eq_temporal_temporal(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return result > 0

    def always_not_equal(self, other):
        """Generated regular ``always_not_equal``.

        MEOS Functions:
            always_ne_temporal_temporal, always_ne_tfloat_float
        """
        from ..tfloat import TFloat

        if isinstance(other, float):
            result = always_ne_tfloat_float(self._inner, other)
        elif isinstance(other, TFloat):
            result = always_ne_temporal_temporal(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return result > 0

    def at(self, other):
        """Generated regular ``at``.

        MEOS Functions:
            tfloat_at_value
        """
        if isinstance(other, (int, float)):
            result = tfloat_at_value(self._inner, float(other))
        elif isinstance(other, IntSet):
            return super().at(other.to_floatset())
        elif isinstance(other, IntSpan):
            return super().at(other.to_floatspan())
        elif isinstance(other, IntSpanSet):
            return super().at(other.to_floatspanset())
        else:
            return super().at(other)
        return Temporal._factory(result)

    def ever_equal(self, other):
        """Generated regular ``ever_equal``.

        MEOS Functions:
            ever_eq_temporal_temporal, ever_eq_tfloat_float
        """
        from ..tfloat import TFloat

        if isinstance(other, float):
            result = ever_eq_tfloat_float(self._inner, other)
        elif isinstance(other, TFloat):
            result = ever_eq_temporal_temporal(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return result > 0

    def ever_not_equal(self, other):
        """Generated regular ``ever_not_equal``.

        MEOS Functions:
            ever_ne_temporal_temporal, ever_ne_tfloat_float
        """
        from ..tfloat import TFloat

        if isinstance(other, float):
            result = ever_ne_tfloat_float(self._inner, other)
        elif isinstance(other, TFloat):
            result = ever_ne_temporal_temporal(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return result > 0

    def minus(self, other):
        """Generated regular ``minus``.

        MEOS Functions:
            tfloat_minus_value
        """
        if isinstance(other, (int, float)):
            result = tfloat_minus_value(self._inner, float(other))
        elif isinstance(other, IntSet):
            return super().minus(other.to_floatset())
        elif isinstance(other, IntSpan):
            return super().minus(other.to_floatspan())
        elif isinstance(other, IntSpanSet):
            return super().minus(other.to_floatspanset())
        else:
            return super().minus(other)
        return Temporal._factory(result)

    def temporal_equal(self, other):
        """Generated regular ``temporal_equal``.

        MEOS Functions:
            teq_tfloat_float
        """
        if isinstance(other, (int, float)):
            result = teq_tfloat_float(self._inner, float(other))
        else:
            return super().temporal_equal(other)
        return Temporal._factory(result)

    def temporal_not_equal(self, other):
        """Generated regular ``temporal_not_equal``.

        MEOS Functions:
            tne_tfloat_float
        """
        if isinstance(other, (int, float)):
            result = tne_tfloat_float(self._inner, float(other))
        else:
            return super().temporal_not_equal(other)
        return Temporal._factory(result)
