# Copyright (c) 2016-2026, Université libre de Bruxelles and PyMEOS
# contributors. Licensed under the PostgreSQL License (see LICENSE).
#
# ============================================================================
#  GENERATED by tools/oo_codegen/codegen.py -- DO NOT EDIT.
#  Regenerate:
#    python3 tools/oo_codegen/codegen.py --mixin ttext \
#        --mixin-out pymeos/main/_generated/ttext_methods.py
# ============================================================================
#
# Wired into pymeos.main.TText via TTextDispatchMixin.  Every method
# dispatches by argument type to the EXACT pymeos_cffi backing the
# hand-written method used -- same native call, same transforms, same
# result, never reimplemented: identical by construction.
"""Generated regular OO methods for the TText family."""
from __future__ import annotations

from typing import TYPE_CHECKING

import shapely.geometry.base as shpb
from pymeos_cffi import *

from ...temporal import Temporal


if TYPE_CHECKING:
    from ..ttext import TText


class TTextDispatchMixin:
    """Generated regular families (comparison, spatial relationship,
    distance, restriction) for :class:`TText`."""

    def always_equal(self, other):
        """Generated regular ``always_equal``.

        MEOS Functions:
            always_eq_temporal_temporal, always_eq_ttext_text
        """
        from ..ttext import TText

        if isinstance(other, str):
            result = always_eq_ttext_text(self._inner, other)
        elif isinstance(other, TText):
            result = always_eq_temporal_temporal(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return result > 0

    def always_not_equal(self, other):
        """Generated regular ``always_not_equal``.

        MEOS Functions:
            always_ne_temporal_temporal, always_ne_ttext_text
        """
        from ..ttext import TText

        if isinstance(other, str):
            result = always_ne_ttext_text(self._inner, other)
        elif isinstance(other, TText):
            result = always_ne_temporal_temporal(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return result > 0

    def at(self, other):
        """Generated regular ``at``.

        MEOS Functions:
            temporal_at_values, ttext_at_value
        """
        if isinstance(other, str):
            result = ttext_at_value(self._inner, other)
        elif isinstance(other, list) and isinstance(other[0], str):
            result = temporal_at_values(self._inner, textset_make(other))
        else:
            return super().at(other)
        return Temporal._factory(result)

    def ever_equal(self, other):
        """Generated regular ``ever_equal``.

        MEOS Functions:
            ever_eq_temporal_temporal, ever_eq_ttext_text
        """
        from ..ttext import TText

        if isinstance(other, str):
            result = ever_eq_ttext_text(self._inner, other)
        elif isinstance(other, TText):
            result = ever_eq_temporal_temporal(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return result > 0

    def ever_not_equal(self, other):
        """Generated regular ``ever_not_equal``.

        MEOS Functions:
            ever_ne_temporal_temporal, ever_ne_ttext_text
        """
        from ..ttext import TText

        if isinstance(other, str):
            result = ever_ne_ttext_text(self._inner, other)
        elif isinstance(other, TText):
            result = ever_ne_temporal_temporal(self._inner, other._inner)
        else:
            raise TypeError(f"Operation not supported with type " f"{other.__class__}")
        return result > 0

    def minus(self, other):
        """Generated regular ``minus``.

        MEOS Functions:
            temporal_minus_values, ttext_minus_value
        """
        if isinstance(other, str):
            result = ttext_minus_value(self._inner, other)
        elif isinstance(other, list) and isinstance(other[0], str):
            result = temporal_minus_values(self._inner, textset_make(other))
        else:
            return super().minus(other)
        return Temporal._factory(result)

    def temporal_equal(self, other):
        """Generated regular ``temporal_equal``.

        MEOS Functions:
            teq_ttext_text
        """
        if isinstance(other, str):
            result = teq_ttext_text(self._inner, other)
        else:
            return super().temporal_equal(other)
        return Temporal._factory(result)

    def temporal_not_equal(self, other):
        """Generated regular ``temporal_not_equal``.

        MEOS Functions:
            tne_ttext_text
        """
        if isinstance(other, str):
            result = tne_ttext_text(self._inner, other)
        else:
            return super().temporal_not_equal(other)
        return Temporal._factory(result)
